// flow-typed signature: 7fe3fe85f4dedb9e293bd17fb474fd9e
// flow-typed version: <<STUB>>/@webcomponents/webcomponentsjs_v2.5.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webcomponents/webcomponentsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webcomponents/webcomponentsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-pf_dom' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-pf_js' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/custom-elements-es5-adapter-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-bundle-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_dom-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_js-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-pf-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/flag-parser' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/baseuri' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/child-node/after' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/child-node/before' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/child-node' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/child-node/remove' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/child-node/replace-with' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/custom-event' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/es6-misc' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/get-attribute-names' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/matches' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/append' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/parent-node' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/prepend' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/replace-children' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/promise' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/svg-element-class-list' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/platform/symbol' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/unresolved' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-bundle' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-ce.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-ce'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-pf_dom.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-pf_dom'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-pf_js.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-pf_js'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd'>;
}
declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/custom-elements-es5-adapter'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/custom-elements-es5-adapter-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/custom-elements-es5-adapter-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-bundle-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-bundle-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-ce-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-ce-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_dom-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_dom-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_js-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-pf_js-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-pf-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-pf-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/entrypoints/webcomponents-sd-index'>;
}
declare module '@webcomponents/webcomponentsjs/src/flag-parser.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/flag-parser'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/baseuri.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/baseuri'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/after.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node/after'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/before.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node/before'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/index' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/remove.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node/remove'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/child-node/replace-with.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/child-node/replace-with'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/custom-event.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/custom-event'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/es6-misc.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/es6-misc'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/get-attribute-names.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/get-attribute-names'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/matches.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/matches'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/append.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/parent-node/append'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/index' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/parent-node'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/parent-node'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/prepend.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/parent-node/prepend'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/parent-node/replace-children.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/parent-node/replace-children'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/promise.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/promise'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/svg-element-class-list.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/svg-element-class-list'>;
}
declare module '@webcomponents/webcomponentsjs/src/platform/symbol.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/platform/symbol'>;
}
declare module '@webcomponents/webcomponentsjs/src/unresolved.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/src/unresolved'>;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-bundle.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/webcomponents-bundle'>;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-loader.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/webcomponents-loader'>;
}
