// flow-typed signature: b2f271ff1775755cdbaf1858a7721e87
// flow-typed version: <<STUB>>/@webcomponents/webcomponentsjs_v^1.0.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webcomponents/webcomponentsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webcomponents/webcomponentsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-pf-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/externs/webcomponents' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/gulpfile' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/post-polyfill' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/pre-polyfill' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/src/unresolved' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/tests/imports/csp-script-1' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/tests/imports/csp-script-2' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/tests/imports/current-script' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-hi-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-hi' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-lite' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-loader' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-sd-ce' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/custom-elements-es5-adapter'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-ce-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-ce-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-pf-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/webcomponents-hi-sd-ce-pf-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index'
  >;
}
declare module '@webcomponents/webcomponentsjs/externs/webcomponents.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/externs/webcomponents'
  >;
}
declare module '@webcomponents/webcomponentsjs/gulpfile.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/gulpfile'>;
}
declare module '@webcomponents/webcomponentsjs/src/post-polyfill.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/src/post-polyfill'
  >;
}
declare module '@webcomponents/webcomponentsjs/src/pre-polyfill.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/src/pre-polyfill'
  >;
}
declare module '@webcomponents/webcomponentsjs/src/unresolved.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/src/unresolved'
  >;
}
declare module '@webcomponents/webcomponentsjs/tests/imports/csp-script-1.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/tests/imports/csp-script-1'
  >;
}
declare module '@webcomponents/webcomponentsjs/tests/imports/csp-script-2.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/tests/imports/csp-script-2'
  >;
}
declare module '@webcomponents/webcomponentsjs/tests/imports/current-script.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/tests/imports/current-script'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-hi-ce.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-hi-ce'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-hi.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-hi'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-lite.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-lite'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-loader.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-loader'
  >;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-sd-ce.js' {
  declare module.exports: $Exports<
    '@webcomponents/webcomponentsjs/webcomponents-sd-ce'
  >;
}
