// flow-typed signature: f91a2106c6dcebbabce37b0ac2da3e13
// flow-typed version: <<STUB>>/@webcomponents/webcomponentsjs_v2.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webcomponents/webcomponentsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webcomponents/webcomponentsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-bundle-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-pf-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-index' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-bundle' {
  declare module.exports: any;
}

declare module '@webcomponents/webcomponentsjs/webcomponents-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-ce.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-ce'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce'>;
}
declare module '@webcomponents/webcomponentsjs/bundles/webcomponents-sd.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/bundles/webcomponents-sd'>;
}
declare module '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/custom-elements-es5-adapter'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-bundle-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/webcomponents-bundle-index'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-ce-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/webcomponents-ce-index'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-pf-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-pf-index'>;
}
declare module '@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-index.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-index'>;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-bundle.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/webcomponents-bundle'>;
}
declare module '@webcomponents/webcomponentsjs/webcomponents-loader.js' {
  declare module.exports: $Exports<'@webcomponents/webcomponentsjs/webcomponents-loader'>;
}
