stages:
  - build
  - deploy

build:
  stage: build
  image: docker:27
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'     
  script:
    - echo "$EBI_REGISTRY_PASSWORD" | docker login -u "$EBI_REGISTRY_USER" --password-stdin dockerhub.ebi.ac.uk
    - docker build -f Dockerfile -t "dockerhub.ebi.ac.uk/interpro/interpro-client:$CI_COMMIT_SHA" .
    - docker push "dockerhub.ebi.ac.uk/interpro/interpro-client:$CI_COMMIT_SHA"

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  variables:
    KUBECONFIG: /tmp/kubeconfig
  before_script:
    - echo "$KUBECONFIG_FILE" | base64 -d > "$KUBECONFIG"
  script:
    - kubectl set image deployment/interpro-client interpro-client="dockerhub.ebi.ac.uk/interpro/interpro-client:$CI_COMMIT_SHA" --kubeconfig="$KUBECONFIG"
    - kubectl rollout status deployment/interpro-client --kubeconfig="$KUBECONFIG" --timeout=120s
  environment:
    name: staging