server {
    listen       8080;
    server_name  _;
    root   /usr/share/nginx/html;

    location = / {
        return 302 /interpro/;
    }

    location /interpro/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /interpro/index.html;
    }
}