// flow-typed signature: a342d6f6968743dec2f6882e7060847d
// flow-typed version: <<STUB>>/@types/d3-scale_v4.0.8/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/d3-scale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/d3-scale' {
  declare module.exports: any;
}
