// flow-typed signature: 2de9ba7fc0af6f5ba831a4162fc13376
// flow-typed version: <<STUB>>/@types/gtag.js_v0.0.18/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/gtag.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/gtag.js' {
  declare module.exports: any;
}
