// flow-typed signature: 0e8d2e75455134052e6f7efe685b6f10
// flow-typed version: <<STUB>>/@types/react-dom_v18.2.18/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
