export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';

export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const RESET_SETTINGS = 'RESET_SETTINGS';

export const LOADING_DATA = 'LOADING_DATA';
export const LOADED_DATA = 'LOADED_DATA';
export const FAILED_LOADING_DATA = 'FAILED_LOADING_DATA';
