// flow-typed signature: 8bd0f2006c45b2e3e0f9d00d04a194bb
// flow-typed version: <<STUB>>/babel-plugin-transform-react-inline-elements_v6.22.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-inline-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-inline-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-inline-elements/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-inline-elements/lib/index' {
  declare module.exports: $Exports<'babel-plugin-transform-react-inline-elements/lib'>;
}
declare module 'babel-plugin-transform-react-inline-elements/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-inline-elements/lib'>;
}
