// flow-typed signature: ec75a279313241d2da290983833b4ca3
// flow-typed version: <<STUB>>/babel-preset-env_v^1.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-env/data/builtInFeatures' {
  declare module.exports: any;
}

declare module 'babel-preset-env/data/electronToChromium' {
  declare module.exports: any;
}

declare module 'babel-preset-env/data/pluginFeatures' {
  declare module.exports: any;
}

declare module 'babel-preset-env/lib/index' {
  declare module.exports: any;
}

declare module 'babel-preset-env/lib/transformPolyfillRequirePlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-env/data/builtInFeatures.js' {
  declare module.exports: $Exports<'babel-preset-env/data/builtInFeatures'>;
}
declare module 'babel-preset-env/data/electronToChromium.js' {
  declare module.exports: $Exports<'babel-preset-env/data/electronToChromium'>;
}
declare module 'babel-preset-env/data/pluginFeatures.js' {
  declare module.exports: $Exports<'babel-preset-env/data/pluginFeatures'>;
}
declare module 'babel-preset-env/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-env/lib/index'>;
}
declare module 'babel-preset-env/lib/transformPolyfillRequirePlugin.js' {
  declare module.exports: $Exports<'babel-preset-env/lib/transformPolyfillRequirePlugin'>;
}
