// flow-typed signature: db091bff0c9e06f7bffcb0244204fc4e
// flow-typed version: <<STUB>>/chrome-launcher_v0.13.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrome-launcher/chrome-launcher' {
  declare module.exports: any;
}

declare module 'chrome-launcher/compiled-check' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist/chrome-finder' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist/chrome-launcher' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist/flags' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist/random-port' {
  declare module.exports: any;
}

declare module 'chrome-launcher/dist/utils' {
  declare module.exports: any;
}

declare module 'chrome-launcher/manual-chrome-launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrome-launcher/chrome-launcher/index' {
  declare module.exports: $Exports<'chrome-launcher/chrome-launcher'>;
}
declare module 'chrome-launcher/chrome-launcher/index.js' {
  declare module.exports: $Exports<'chrome-launcher/chrome-launcher'>;
}
declare module 'chrome-launcher/compiled-check.js' {
  declare module.exports: $Exports<'chrome-launcher/compiled-check'>;
}
declare module 'chrome-launcher/dist/chrome-finder.js' {
  declare module.exports: $Exports<'chrome-launcher/dist/chrome-finder'>;
}
declare module 'chrome-launcher/dist/chrome-launcher.js' {
  declare module.exports: $Exports<'chrome-launcher/dist/chrome-launcher'>;
}
declare module 'chrome-launcher/dist/flags.js' {
  declare module.exports: $Exports<'chrome-launcher/dist/flags'>;
}
declare module 'chrome-launcher/dist/index' {
  declare module.exports: $Exports<'chrome-launcher/dist'>;
}
declare module 'chrome-launcher/dist/index.js' {
  declare module.exports: $Exports<'chrome-launcher/dist'>;
}
declare module 'chrome-launcher/dist/random-port.js' {
  declare module.exports: $Exports<'chrome-launcher/dist/random-port'>;
}
declare module 'chrome-launcher/dist/utils.js' {
  declare module.exports: $Exports<'chrome-launcher/dist/utils'>;
}
declare module 'chrome-launcher/manual-chrome-launcher.js' {
  declare module.exports: $Exports<'chrome-launcher/manual-chrome-launcher'>;
}
