// flow-typed signature: 462f329539121a824c763edb23ffde7c
// flow-typed version: <<STUB>>/clanviewer_v^0.1.11/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clanviewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clanviewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clanviewer/biojs/example' {
  declare module.exports: any;
}

declare module 'clanviewer/build/clanviewer.packed' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'clanviewer/examples/index' {
  declare module.exports: any;
}

declare module 'clanviewer/examples/simple' {
  declare module.exports: any;
}

declare module 'clanviewer/lib/index' {
  declare module.exports: any;
}

declare module 'clanviewer/lib/index.test' {
  declare module.exports: any;
}

declare module 'clanviewer/test/functional_tests' {
  declare module.exports: any;
}

declare module 'clanviewer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clanviewer/biojs/example.js' {
  declare module.exports: $Exports<'clanviewer/biojs/example'>;
}
declare module 'clanviewer/build/clanviewer.packed.js' {
  declare module.exports: $Exports<'clanviewer/build/clanviewer.packed'>;
}
declare module 'clanviewer/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/block-navigation'>;
}
declare module 'clanviewer/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/prettify'>;
}
declare module 'clanviewer/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/sorter'>;
}
declare module 'clanviewer/examples/index.js' {
  declare module.exports: $Exports<'clanviewer/examples/index'>;
}
declare module 'clanviewer/examples/simple.js' {
  declare module.exports: $Exports<'clanviewer/examples/simple'>;
}
declare module 'clanviewer/lib/index.js' {
  declare module.exports: $Exports<'clanviewer/lib/index'>;
}
declare module 'clanviewer/lib/index.test.js' {
  declare module.exports: $Exports<'clanviewer/lib/index.test'>;
}
declare module 'clanviewer/test/functional_tests.js' {
  declare module.exports: $Exports<'clanviewer/test/functional_tests'>;
}
declare module 'clanviewer/webpack.config.js' {
  declare module.exports: $Exports<'clanviewer/webpack.config'>;
}
