// flow-typed signature: 783a605a549f52e95b3b358973c0d48a
// flow-typed version: <<STUB>>/clanviewer_v0.2.4/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clanviewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clanviewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clanviewer/biojs/example' {
  declare module.exports: any;
}

declare module 'clanviewer/examples' {
  declare module.exports: any;
}

declare module 'clanviewer/examples/simple' {
  declare module.exports: any;
}

declare module 'clanviewer/lib' {
  declare module.exports: any;
}

declare module 'clanviewer/lib/index.test' {
  declare module.exports: any;
}

declare module 'clanviewer/test/functional_tests' {
  declare module.exports: any;
}

declare module 'clanviewer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clanviewer/biojs/example.js' {
  declare module.exports: $Exports<'clanviewer/biojs/example'>;
}
declare module 'clanviewer/examples/index' {
  declare module.exports: $Exports<'clanviewer/examples'>;
}
declare module 'clanviewer/examples/index.js' {
  declare module.exports: $Exports<'clanviewer/examples'>;
}
declare module 'clanviewer/examples/simple.js' {
  declare module.exports: $Exports<'clanviewer/examples/simple'>;
}
declare module 'clanviewer/lib/index' {
  declare module.exports: $Exports<'clanviewer/lib'>;
}
declare module 'clanviewer/lib/index.js' {
  declare module.exports: $Exports<'clanviewer/lib'>;
}
declare module 'clanviewer/lib/index.test.js' {
  declare module.exports: $Exports<'clanviewer/lib/index.test'>;
}
declare module 'clanviewer/test/functional_tests.js' {
  declare module.exports: $Exports<'clanviewer/test/functional_tests'>;
}
declare module 'clanviewer/webpack.config.js' {
  declare module.exports: $Exports<'clanviewer/webpack.config'>;
}
