// flow-typed signature: 7189d7a09e7b8ae2a326db5435b61dff
// flow-typed version: <<STUB>>/clanviewer_v1.1.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clanviewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clanviewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clanviewer/build/clanviewer.packed' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'clanviewer/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'clanviewer/css/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module 'clanviewer/examples/simple' {
  declare module.exports: any;
}

declare module 'clanviewer/jest.config' {
  declare module.exports: any;
}

declare module 'clanviewer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clanviewer/build/clanviewer.packed.js' {
  declare module.exports: $Exports<'clanviewer/build/clanviewer.packed'>;
}
declare module 'clanviewer/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/block-navigation'>;
}
declare module 'clanviewer/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/prettify'>;
}
declare module 'clanviewer/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'clanviewer/coverage/lcov-report/sorter'>;
}
declare module 'clanviewer/css/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'clanviewer/css/__mocks__/styleMock'>;
}
declare module 'clanviewer/examples/simple.js' {
  declare module.exports: $Exports<'clanviewer/examples/simple'>;
}
declare module 'clanviewer/jest.config.js' {
  declare module.exports: $Exports<'clanviewer/jest.config'>;
}
declare module 'clanviewer/webpack.config.js' {
  declare module.exports: $Exports<'clanviewer/webpack.config'>;
}
