// flow-typed signature: 7b039a8ca66fc02f9cbf8b4f33314068
// flow-typed version: <<STUB>>/data-loader_v0.3.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'data-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'data-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'data-loader/dist/index' {
  declare module.exports: any;
}

declare module 'data-loader/src/data-loader' {
  declare module.exports: any;
}

declare module 'data-loader/src/index' {
  declare module.exports: any;
}

declare module 'data-loader/src/request-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'data-loader/dist/index.js' {
  declare module.exports: $Exports<'data-loader/dist/index'>;
}
declare module 'data-loader/src/data-loader.js' {
  declare module.exports: $Exports<'data-loader/src/data-loader'>;
}
declare module 'data-loader/src/index.js' {
  declare module.exports: $Exports<'data-loader/src/index'>;
}
declare module 'data-loader/src/request-manager.js' {
  declare module.exports: $Exports<'data-loader/src/request-manager'>;
}
