// flow-typed signature: fd7adebc0a643efa9cbace5307387138
// flow-typed version: <<STUB>>/details-element-polyfill_v2.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'details-element-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'details-element-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'details-element-polyfill/dist/details-element-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'details-element-polyfill/dist/details-element-polyfill.js' {
  declare module.exports: $Exports<'details-element-polyfill/dist/details-element-polyfill'>;
}
