// flow-typed signature: e572adbde88ca05d4712717d55228897
// flow-typed version: <<STUB>>/EBI-Icon-fonts_v1.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'EBI-Icon-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'EBI-Icon-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'EBI-Icon-fonts/EBI-Chemistry/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-Conceptual/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-FileFormats/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-Functional/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-Generic/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-SocialMedia/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/EBI-Species/static/grunticon.loader' {
  declare module.exports: any;
}

declare module 'EBI-Icon-fonts/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'EBI-Icon-fonts/EBI-Chemistry/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-Chemistry/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-Conceptual/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-Conceptual/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-FileFormats/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-FileFormats/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-Functional/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-Functional/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-Generic/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-Generic/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-SocialMedia/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-SocialMedia/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/EBI-Species/static/grunticon.loader.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/EBI-Species/static/grunticon.loader'>;
}
declare module 'EBI-Icon-fonts/Gruntfile.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/Gruntfile'>;
}
