// flow-typed signature: 2e3cd37016eaf2c1d11e7286fa9176a3
// flow-typed version: <<STUB>>/ebi-framework_v1.3.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ebi-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ebi-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ebi-framework/css/styleguide/kss-assets/kss-fullscreen' {
  declare module.exports: any;
}

declare module 'ebi-framework/css/styleguide/kss-assets/kss-guides' {
  declare module.exports: any;
}

declare module 'ebi-framework/css/styleguide/kss-assets/kss-markup' {
  declare module.exports: any;
}

declare module 'ebi-framework/css/styleguide/kss-assets/kss' {
  declare module.exports: any;
}

declare module 'ebi-framework/css/styleguide/kss-assets/prettify' {
  declare module.exports: any;
}

declare module 'ebi-framework/css/styleguide/kss-assets/scrollspy' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/1_about' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/2_ebiFrameworkExternalLinks' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/3_ebiFrameworkForms' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/4_ebiFrameworkContent' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/5_ebiFrameworkCookieBanner' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/ebi-global-includes/script/6_ebiFrameworkInvokeScripts' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/elixirBanner' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/elixirBanner.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/foundationExtendEBI' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/foundationExtendEBI.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/script' {
  declare module.exports: any;
}

declare module 'ebi-framework/js/script.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/Choices/assets/scripts/dist/choices' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/Choices/assets/scripts/dist/choices.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.abide' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.accordion' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.core' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.interchange' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.magellan' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.orbit' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.plugin' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.positionable' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveAccordionTabs' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.reveal' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.slider' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.smoothScroll' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.sticky' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.tabs' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.toggler' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.box' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.core' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.imageLoader' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.timer' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/LiveFilter/js/jquery.liveFilter' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/dist/motion-ui' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/dist/motion-ui.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/gulpfile' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/lib/handlebars' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui.min' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/gulpfile' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/lib/handlebars' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/motion-ui' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/motion-ui/motion-ui' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/extras/jquery.dragtable.mod' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/extras/jquery.metadata' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/extras/semver-mod' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/extras/semver' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.combined' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.widgets' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-extract' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-iso8601' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-month' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-range' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-two-digit-year' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-weekday' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-duration' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-feet-inch-fraction' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-file-type' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-globalize' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-huge-numbers' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-ignore-articles' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-image' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-input-select' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-metric' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-named-numbers' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-network' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-roman' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-alignChar' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-build-table' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-chart' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-columns' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-columnSelector' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-cssStickyHeaders' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-editable' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-html5' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-jui' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-select2' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-type-insideRange' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-formatter' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-grouping' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-headerTitles' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-lazyload' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-math' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-output' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-pager' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-print' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-reflow' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-repeatheaders' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-resizable' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-saveSort' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-scroller' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-sort2Hash' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-sortTbodies' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-staticRow' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-stickyHeaders' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-storage' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-toggle' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-uitheme' {
  declare module.exports: any;
}

declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ebi-framework/css/styleguide/kss-assets/kss-fullscreen.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/kss-fullscreen'>;
}
declare module 'ebi-framework/css/styleguide/kss-assets/kss-guides.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/kss-guides'>;
}
declare module 'ebi-framework/css/styleguide/kss-assets/kss-markup.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/kss-markup'>;
}
declare module 'ebi-framework/css/styleguide/kss-assets/kss.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/kss'>;
}
declare module 'ebi-framework/css/styleguide/kss-assets/prettify.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/prettify'>;
}
declare module 'ebi-framework/css/styleguide/kss-assets/scrollspy.js' {
  declare module.exports: $Exports<'ebi-framework/css/styleguide/kss-assets/scrollspy'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/1_about.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/1_about'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/2_ebiFrameworkExternalLinks.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/2_ebiFrameworkExternalLinks'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/3_ebiFrameworkForms.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/3_ebiFrameworkForms'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/4_ebiFrameworkContent.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/4_ebiFrameworkContent'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/5_ebiFrameworkCookieBanner.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/5_ebiFrameworkCookieBanner'>;
}
declare module 'ebi-framework/js/ebi-global-includes/script/6_ebiFrameworkInvokeScripts.js' {
  declare module.exports: $Exports<'ebi-framework/js/ebi-global-includes/script/6_ebiFrameworkInvokeScripts'>;
}
declare module 'ebi-framework/js/elixirBanner.js' {
  declare module.exports: $Exports<'ebi-framework/js/elixirBanner'>;
}
declare module 'ebi-framework/js/elixirBanner.min.js' {
  declare module.exports: $Exports<'ebi-framework/js/elixirBanner.min'>;
}
declare module 'ebi-framework/js/foundationExtendEBI.js' {
  declare module.exports: $Exports<'ebi-framework/js/foundationExtendEBI'>;
}
declare module 'ebi-framework/js/foundationExtendEBI.min.js' {
  declare module.exports: $Exports<'ebi-framework/js/foundationExtendEBI.min'>;
}
declare module 'ebi-framework/js/script.js' {
  declare module.exports: $Exports<'ebi-framework/js/script'>;
}
declare module 'ebi-framework/js/script.min.js' {
  declare module.exports: $Exports<'ebi-framework/js/script.min'>;
}
declare module 'ebi-framework/libraries/Choices/assets/scripts/dist/choices.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/Choices/assets/scripts/dist/choices'>;
}
declare module 'ebi-framework/libraries/Choices/assets/scripts/dist/choices.min.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/Choices/assets/scripts/dist/choices.min'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.abide.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.abide'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.accordion.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.accordion'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.accordionMenu'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.core.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.core'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.drilldown.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.drilldown'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.dropdown.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.dropdown'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.dropdownMenu'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.equalizer.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.equalizer'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.interchange.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.interchange'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.magellan.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.magellan'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.min.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.min'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.offcanvas.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.offcanvas'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.orbit.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.orbit'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.plugin.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.plugin'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.positionable.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.positionable'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveAccordionTabs.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.responsiveAccordionTabs'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.responsiveMenu'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.responsiveToggle'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.reveal.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.reveal'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.slider.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.slider'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.smoothScroll.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.smoothScroll'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.sticky.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.sticky'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.tabs.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.tabs'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.toggler.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.toggler'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.tooltip.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.tooltip'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.box.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.box'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.core.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.core'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.imageLoader.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.imageLoader'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.keyboard'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.mediaQuery'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.motion.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.motion'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.nest.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.nest'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.timer.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.timer'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.touch.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.touch'>;
}
declare module 'ebi-framework/libraries/foundation-6/js/foundation.util.triggers.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/foundation-6/js/foundation.util.triggers'>;
}
declare module 'ebi-framework/libraries/LiveFilter/js/jquery.liveFilter.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/LiveFilter/js/jquery.liveFilter'>;
}
declare module 'ebi-framework/libraries/motion-ui/dist/motion-ui.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/dist/motion-ui'>;
}
declare module 'ebi-framework/libraries/motion-ui/dist/motion-ui.min.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/dist/motion-ui.min'>;
}
declare module 'ebi-framework/libraries/motion-ui/gulpfile.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/gulpfile'>;
}
declare module 'ebi-framework/libraries/motion-ui/lib/handlebars.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/lib/handlebars'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui.min.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/dist/motion-ui.min'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/gulpfile.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/gulpfile'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/lib/handlebars.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/lib/handlebars'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/motion-ui.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui-1.2.2/motion-ui'>;
}
declare module 'ebi-framework/libraries/motion-ui/motion-ui.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/motion-ui/motion-ui'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/extras/jquery.dragtable.mod.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/extras/jquery.dragtable.mod'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/extras/jquery.metadata.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/extras/jquery.metadata'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/extras/semver-mod.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/extras/semver-mod'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/extras/semver.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/extras/semver'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.combined.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.combined'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/jquery.tablesorter'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.widgets.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/jquery.tablesorter.widgets'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-extract.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-extract'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-iso8601.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-iso8601'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-month.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-month'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-range.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-range'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-two-digit-year.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-two-digit-year'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date-weekday.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date-weekday'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-date.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-date'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-duration.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-duration'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-feet-inch-fraction.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-feet-inch-fraction'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-file-type.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-file-type'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-globalize.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-globalize'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-huge-numbers.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-huge-numbers'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-ignore-articles.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-ignore-articles'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-image.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-image'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-input-select.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-input-select'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-metric.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-metric'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-named-numbers.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-named-numbers'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-network.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-network'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/parsers/parser-roman.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/parsers/parser-roman'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-alignChar.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-alignChar'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-build-table.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-build-table'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-chart.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-chart'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-columns.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-columns'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-columnSelector.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-columnSelector'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-cssStickyHeaders.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-cssStickyHeaders'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-editable.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-editable'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-html5.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-html5'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-jui.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-jui'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-select2.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-formatter-select2'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-type-insideRange.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-filter-type-insideRange'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-filter.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-filter'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-formatter.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-formatter'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-grouping.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-grouping'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-headerTitles.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-headerTitles'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-lazyload.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-lazyload'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-math.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-math'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-output.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-output'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-pager.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-pager'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-print.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-print'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-reflow.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-reflow'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-repeatheaders.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-repeatheaders'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-resizable.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-resizable'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-saveSort.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-saveSort'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-scroller.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-scroller'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-sort2Hash.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-sort2Hash'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-sortTbodies.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-sortTbodies'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-staticRow.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-staticRow'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-stickyHeaders.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-stickyHeaders'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-storage.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-storage'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-toggle.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-toggle'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-uitheme.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-uitheme'>;
}
declare module 'ebi-framework/libraries/tablesorter/js/widgets/widget-view.js' {
  declare module.exports: $Exports<'ebi-framework/libraries/tablesorter/js/widgets/widget-view'>;
}
