// flow-typed signature: d8506aac53d07eb535018af23d592d7b
// flow-typed version: <<STUB>>/EBI-Icon-fonts_v1.3.0-rc.3.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'EBI-Icon-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'EBI-Icon-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'EBI-Icon-fonts/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'EBI-Icon-fonts/Gruntfile.js' {
  declare module.exports: $Exports<'EBI-Icon-fonts/Gruntfile'>;
}
