// flow-typed signature: 13e1c76986f437c7a170660b86e415b6
// flow-typed version: <<STUB>>/fake-indexeddb_v5.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fake-indexeddb/auto' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/fakeIndexedDB' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/FDBVersionChangeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/binarySearch' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/canInjectKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/cmp' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/Database' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/enforceRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/errors' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/extractKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/FakeDOMStringList' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/FakeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/FakeEventTarget' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/Index' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/KeyGenerator' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/ObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/RecordStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/scheduling' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/types' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/validateKeyPath' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/valueToKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/cjs/lib/valueToKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/fakeIndexedDB' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/FDBVersionChangeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/binarySearch' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/canInjectKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/cmp' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/Database' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/enforceRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/errors' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/extractKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/FakeDOMStringList' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/FakeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/FakeEventTarget' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/Index' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/KeyGenerator' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/ObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/RecordStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/scheduling' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/types' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/validateKeyPath' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/valueToKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/esm/lib/valueToKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBVersionChangeEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fake-indexeddb/auto/index' {
  declare module.exports: $Exports<'fake-indexeddb/auto'>;
}
declare module 'fake-indexeddb/auto/index.js' {
  declare module.exports: $Exports<'fake-indexeddb/auto'>;
}
declare module 'fake-indexeddb/build/cjs/fakeIndexedDB.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/fakeIndexedDB'>;
}
declare module 'fake-indexeddb/build/cjs/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBCursor'>;
}
declare module 'fake-indexeddb/build/cjs/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/build/cjs/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBDatabase'>;
}
declare module 'fake-indexeddb/build/cjs/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBFactory'>;
}
declare module 'fake-indexeddb/build/cjs/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBIndex'>;
}
declare module 'fake-indexeddb/build/cjs/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBKeyRange'>;
}
declare module 'fake-indexeddb/build/cjs/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBObjectStore'>;
}
declare module 'fake-indexeddb/build/cjs/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/build/cjs/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBRequest'>;
}
declare module 'fake-indexeddb/build/cjs/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBTransaction'>;
}
declare module 'fake-indexeddb/build/cjs/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/FDBVersionChangeEvent'>;
}
declare module 'fake-indexeddb/build/cjs/index' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs'>;
}
declare module 'fake-indexeddb/build/cjs/index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs'>;
}
declare module 'fake-indexeddb/build/cjs/lib/binarySearch.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/binarySearch'>;
}
declare module 'fake-indexeddb/build/cjs/lib/canInjectKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/canInjectKey'>;
}
declare module 'fake-indexeddb/build/cjs/lib/cmp.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/cmp'>;
}
declare module 'fake-indexeddb/build/cjs/lib/Database.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/Database'>;
}
declare module 'fake-indexeddb/build/cjs/lib/enforceRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/enforceRange'>;
}
declare module 'fake-indexeddb/build/cjs/lib/errors.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/errors'>;
}
declare module 'fake-indexeddb/build/cjs/lib/extractKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/extractKey'>;
}
declare module 'fake-indexeddb/build/cjs/lib/FakeDOMStringList.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/FakeDOMStringList'>;
}
declare module 'fake-indexeddb/build/cjs/lib/FakeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/FakeEvent'>;
}
declare module 'fake-indexeddb/build/cjs/lib/FakeEventTarget.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/FakeEventTarget'>;
}
declare module 'fake-indexeddb/build/cjs/lib/Index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/Index'>;
}
declare module 'fake-indexeddb/build/cjs/lib/KeyGenerator.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/KeyGenerator'>;
}
declare module 'fake-indexeddb/build/cjs/lib/ObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/ObjectStore'>;
}
declare module 'fake-indexeddb/build/cjs/lib/RecordStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/RecordStore'>;
}
declare module 'fake-indexeddb/build/cjs/lib/scheduling.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/scheduling'>;
}
declare module 'fake-indexeddb/build/cjs/lib/types.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/types'>;
}
declare module 'fake-indexeddb/build/cjs/lib/validateKeyPath.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/validateKeyPath'>;
}
declare module 'fake-indexeddb/build/cjs/lib/valueToKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/valueToKey'>;
}
declare module 'fake-indexeddb/build/cjs/lib/valueToKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/cjs/lib/valueToKeyRange'>;
}
declare module 'fake-indexeddb/build/esm/fakeIndexedDB.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/fakeIndexedDB'>;
}
declare module 'fake-indexeddb/build/esm/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBCursor'>;
}
declare module 'fake-indexeddb/build/esm/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/build/esm/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBDatabase'>;
}
declare module 'fake-indexeddb/build/esm/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBFactory'>;
}
declare module 'fake-indexeddb/build/esm/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBIndex'>;
}
declare module 'fake-indexeddb/build/esm/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBKeyRange'>;
}
declare module 'fake-indexeddb/build/esm/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBObjectStore'>;
}
declare module 'fake-indexeddb/build/esm/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/build/esm/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBRequest'>;
}
declare module 'fake-indexeddb/build/esm/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBTransaction'>;
}
declare module 'fake-indexeddb/build/esm/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/FDBVersionChangeEvent'>;
}
declare module 'fake-indexeddb/build/esm/index' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm'>;
}
declare module 'fake-indexeddb/build/esm/index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm'>;
}
declare module 'fake-indexeddb/build/esm/lib/binarySearch.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/binarySearch'>;
}
declare module 'fake-indexeddb/build/esm/lib/canInjectKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/canInjectKey'>;
}
declare module 'fake-indexeddb/build/esm/lib/cmp.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/cmp'>;
}
declare module 'fake-indexeddb/build/esm/lib/Database.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/Database'>;
}
declare module 'fake-indexeddb/build/esm/lib/enforceRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/enforceRange'>;
}
declare module 'fake-indexeddb/build/esm/lib/errors.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/errors'>;
}
declare module 'fake-indexeddb/build/esm/lib/extractKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/extractKey'>;
}
declare module 'fake-indexeddb/build/esm/lib/FakeDOMStringList.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/FakeDOMStringList'>;
}
declare module 'fake-indexeddb/build/esm/lib/FakeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/FakeEvent'>;
}
declare module 'fake-indexeddb/build/esm/lib/FakeEventTarget.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/FakeEventTarget'>;
}
declare module 'fake-indexeddb/build/esm/lib/Index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/Index'>;
}
declare module 'fake-indexeddb/build/esm/lib/KeyGenerator.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/KeyGenerator'>;
}
declare module 'fake-indexeddb/build/esm/lib/ObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/ObjectStore'>;
}
declare module 'fake-indexeddb/build/esm/lib/RecordStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/RecordStore'>;
}
declare module 'fake-indexeddb/build/esm/lib/scheduling.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/scheduling'>;
}
declare module 'fake-indexeddb/build/esm/lib/types.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/types'>;
}
declare module 'fake-indexeddb/build/esm/lib/validateKeyPath.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/validateKeyPath'>;
}
declare module 'fake-indexeddb/build/esm/lib/valueToKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/valueToKey'>;
}
declare module 'fake-indexeddb/build/esm/lib/valueToKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/esm/lib/valueToKeyRange'>;
}
declare module 'fake-indexeddb/lib/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursor'>;
}
declare module 'fake-indexeddb/lib/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/lib/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBDatabase'>;
}
declare module 'fake-indexeddb/lib/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBFactory'>;
}
declare module 'fake-indexeddb/lib/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBIndex'>;
}
declare module 'fake-indexeddb/lib/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBKeyRange'>;
}
declare module 'fake-indexeddb/lib/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBObjectStore'>;
}
declare module 'fake-indexeddb/lib/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBTransaction'>;
}
declare module 'fake-indexeddb/lib/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBVersionChangeEvent'>;
}
