// flow-typed signature: 8b510f012ffd4ef8d72d8a42e409c74f
// flow-typed version: <<STUB>>/favicons_v7.1.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons' {
  declare module.exports: any;
}
