// flow-typed signature: f75536557f2063f4d1bee736e322f402
// flow-typed version: <<STUB>>/favicons-webpack-plugin_v5.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'favicons-webpack-plugin/src/cache' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/src/hash' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/src' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/src/logger' {
  declare module.exports: any;
}

declare module 'favicons-webpack-plugin/src/oracle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'favicons-webpack-plugin/src/cache.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src/cache'>;
}
declare module 'favicons-webpack-plugin/src/hash.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src/hash'>;
}
declare module 'favicons-webpack-plugin/src/index' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src'>;
}
declare module 'favicons-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src'>;
}
declare module 'favicons-webpack-plugin/src/logger.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src/logger'>;
}
declare module 'favicons-webpack-plugin/src/oracle.js' {
  declare module.exports: $Exports<'favicons-webpack-plugin/src/oracle'>;
}
