// flow-typed signature: 8fe5f5a1343fcd94de5da0d0a6e9687e
// flow-typed version: <<STUB>>/favicons_v7.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons' {
  declare module.exports: any;
}
