// flow-typed signature: 11253c6e099219368681c33ba1446db1
// flow-typed version: <<STUB>>/favicons_v^6.2.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'favicons/dist/config/html' {
  declare module.exports: any;
}

declare module 'favicons/dist/helpers' {
  declare module.exports: any;
}

declare module 'favicons/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'favicons/dist/config/html.js' {
  declare module.exports: $Exports<'favicons/dist/config/html'>;
}
declare module 'favicons/dist/helpers.js' {
  declare module.exports: $Exports<'favicons/dist/helpers'>;
}
declare module 'favicons/dist/index' {
  declare module.exports: $Exports<'favicons/dist'>;
}
declare module 'favicons/dist/index.js' {
  declare module.exports: $Exports<'favicons/dist'>;
}
