// flow-typed signature: 813dd3f611b5a3f95580acaff29fe468
// flow-typed version: <<STUB>>/filesize_v10.0.6/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filesize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'filesize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'filesize/dist/filesize.esm' {
  declare module.exports: any;
}

declare module 'filesize/dist/filesize.esm.min' {
  declare module.exports: any;
}

declare module 'filesize/dist/filesize' {
  declare module.exports: any;
}

declare module 'filesize/dist/filesize.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'filesize/dist/filesize.esm.js' {
  declare module.exports: $Exports<'filesize/dist/filesize.esm'>;
}
declare module 'filesize/dist/filesize.esm.min.js' {
  declare module.exports: $Exports<'filesize/dist/filesize.esm.min'>;
}
declare module 'filesize/dist/filesize.js' {
  declare module.exports: $Exports<'filesize/dist/filesize'>;
}
declare module 'filesize/dist/filesize.min.js' {
  declare module.exports: $Exports<'filesize/dist/filesize.min'>;
}
