// flow-typed signature: 96b79a8ca729be152c8da2351b7cd371
// flow-typed version: <<STUB>>/file-loader_v6.1.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'file-loader/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-loader/dist/cjs.js' {
  declare module.exports: $Exports<'file-loader/dist/cjs'>;
}
declare module 'file-loader/dist/index' {
  declare module.exports: $Exports<'file-loader/dist'>;
}
declare module 'file-loader/dist/index.js' {
  declare module.exports: $Exports<'file-loader/dist'>;
}
