// flow-typed signature: b56205a094e36f148921b33040de2e68
// flow-typed version: <<STUB>>/fork-ts-checker-webpack-plugin_v9.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fork-ts-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fork-ts-checker-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fork-ts-checker-webpack-plugin/lib/files-change' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/files-match' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/basic-formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/code-frame-formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter-config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter-options' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/stats-formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/types/babel__code-frame' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/webpack-formatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/intercept-done-to-get-dev-server-tap' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-add-dependencies' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-environment-to-patch-watching' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-done-to-async-get-issues' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-error-to-log-message' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-start-to-run-workers' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-stop-to-terminate-workers' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/infrastructure-logger' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-location' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-match' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-options' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-position' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-predicate' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-severity' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/logger' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin-config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin-hooks' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin-options' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin-pools' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin-state' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc/rpc-error' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc/rpc-worker' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc/types' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/rpc/wrap-rpc' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-config-overwrite' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-diagnostics-options' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-support' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-options' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-dependencies-worker' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-issues-worker' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/artifacts' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/dependencies' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/diagnostics' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/emit' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/file-system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/mem-file-system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/passive-file-system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/real-file-system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/compiler-host' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-compiler-host' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-solution-builder-host' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/performance' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/program' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/solution-builder' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/watch-program' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tracing' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tsbuildinfo' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/typescript' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/worker-config' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/abort-error' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/controlled-promise' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/is-pending' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/pool' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/wait' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/forward-slash' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/is-inside-another-path' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/relative-to-context' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/watch/inclusive-node-watch-file-system' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/watch/watch-file-system' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fork-ts-checker-webpack-plugin/lib/files-change.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/files-change'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/files-match.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/files-match'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/basic-formatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/basic-formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/code-frame-formatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/code-frame-formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter-config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/formatter-config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter-options.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/formatter-options'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/formatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/index' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/stats-formatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/stats-formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/types/babel__code-frame.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/types/babel__code-frame'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/webpack-formatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/webpack-formatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/intercept-done-to-get-dev-server-tap.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/intercept-done-to-get-dev-server-tap'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-add-dependencies.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-add-dependencies'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-environment-to-patch-watching.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-after-environment-to-patch-watching'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-done-to-async-get-issues.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-done-to-async-get-issues'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-error-to-log-message.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-error-to-log-message'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-start-to-run-workers.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-start-to-run-workers'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/hooks/tap-stop-to-terminate-workers.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/hooks/tap-stop-to-terminate-workers'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/index' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/infrastructure-logger.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/infrastructure-logger'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/index' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-location.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-location'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-match.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-match'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-options.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-options'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-position.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-position'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-predicate.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-predicate'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-severity.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-severity'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/issue/issue.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/issue/issue'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/logger.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/logger'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin-config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin-config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin-hooks.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin-hooks'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin-options.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin-options'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin-pools.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin-pools'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin-state.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin-state'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/plugin'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/index' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/rpc-error.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc/rpc-error'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/rpc-worker.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc/rpc-worker'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/types.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc/types'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/rpc/wrap-rpc.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/rpc/wrap-rpc'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-config-overwrite.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/type-script-config-overwrite'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-diagnostics-options.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/type-script-diagnostics-options'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-support.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/type-script-support'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-options.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/type-script-worker-options'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-dependencies-worker.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-dependencies-worker'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-issues-worker.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/get-issues-worker'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/artifacts.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/artifacts'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/dependencies.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/dependencies'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/diagnostics.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/diagnostics'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/emit.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/emit'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/file-system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/mem-file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/mem-file-system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/passive-file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/passive-file-system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/real-file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/file-system/real-file-system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/compiler-host.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/compiler-host'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-compiler-host.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-compiler-host'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-solution-builder-host.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/host/watch-solution-builder-host'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/performance.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/performance'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/program.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/program'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/solution-builder.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/solution-builder'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/watch-program.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/program/watch-program'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tracing.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tracing'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tsbuildinfo.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/tsbuildinfo'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/typescript.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/typescript'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/worker-config.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/typescript/worker/lib/worker-config'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/abort-error.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/async/abort-error'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/controlled-promise.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/async/controlled-promise'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/is-pending.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/async/is-pending'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/pool.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/async/pool'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/async/wait.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/async/wait'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/forward-slash.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/path/forward-slash'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/is-inside-another-path.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/path/is-inside-another-path'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/utils/path/relative-to-context.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/utils/path/relative-to-context'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/watch/inclusive-node-watch-file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/watch/inclusive-node-watch-file-system'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/watch/watch-file-system.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/watch/watch-file-system'>;
}
