// flow-typed signature: b6db398772f36d6c517692470f1c858f
// flow-typed version: <<STUB>>/glob-loader_v0.3.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'glob-loader/index' {
  declare module.exports: $Exports<'glob-loader'>;
}
declare module 'glob-loader/index.js' {
  declare module.exports: $Exports<'glob-loader'>;
}
