// flow-typed signature: 8d00e017bfce959c234d0ba87b913fee
// flow-typed version: <<STUB>>/idb_v3.0.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb/build/idb' {
  declare module.exports: any;
}

declare module 'idb/gulpfile' {
  declare module.exports: any;
}

declare module 'idb/lib/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb/build/idb.js' {
  declare module.exports: $Exports<'idb/build/idb'>;
}
declare module 'idb/gulpfile.js' {
  declare module.exports: $Exports<'idb/gulpfile'>;
}
declare module 'idb/lib/node.js' {
  declare module.exports: $Exports<'idb/lib/node'>;
}
