// flow-typed signature: c2769ed235bf7f23e4831a4a6ae5795c
// flow-typed version: <<STUB>>/idb_v^2.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb/gulpfile' {
  declare module.exports: any;
}

declare module 'idb/lib/idb' {
  declare module.exports: any;
}

declare module 'idb/lib/node' {
  declare module.exports: any;
}

declare module 'idb/test/idb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb/gulpfile.js' {
  declare module.exports: $Exports<'idb/gulpfile'>;
}
declare module 'idb/lib/idb.js' {
  declare module.exports: $Exports<'idb/lib/idb'>;
}
declare module 'idb/lib/node.js' {
  declare module.exports: $Exports<'idb/lib/node'>;
}
declare module 'idb/test/idb.js' {
  declare module.exports: $Exports<'idb/test/idb'>;
}
