// flow-typed signature: e6ab5eeaf3712233ea92a1cc01c6140f
// flow-typed version: <<STUB>>/idb_v7.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb/build/async-iterators' {
  declare module.exports: any;
}

declare module 'idb/build' {
  declare module.exports: any;
}

declare module 'idb/build/umd-with-async-ittr' {
  declare module.exports: any;
}

declare module 'idb/build/umd' {
  declare module.exports: any;
}

declare module 'idb/build/wrap-idb-value' {
  declare module.exports: any;
}

declare module 'idb/with-async-ittr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb/build/async-iterators.js' {
  declare module.exports: $Exports<'idb/build/async-iterators'>;
}
declare module 'idb/build/index' {
  declare module.exports: $Exports<'idb/build'>;
}
declare module 'idb/build/index.js' {
  declare module.exports: $Exports<'idb/build'>;
}
declare module 'idb/build/umd-with-async-ittr.js' {
  declare module.exports: $Exports<'idb/build/umd-with-async-ittr'>;
}
declare module 'idb/build/umd.js' {
  declare module.exports: $Exports<'idb/build/umd'>;
}
declare module 'idb/build/wrap-idb-value.js' {
  declare module.exports: $Exports<'idb/build/wrap-idb-value'>;
}
declare module 'idb/with-async-ittr.js' {
  declare module.exports: $Exports<'idb/with-async-ittr'>;
}
