// flow-typed signature: 22da85abea070a45db6e31ce9edf1c90
// flow-typed version: <<STUB>>/iltorb_v2.0.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iltorb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iltorb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'iltorb/index' {
  declare module.exports: $Exports<'iltorb'>;
}
declare module 'iltorb/index.js' {
  declare module.exports: $Exports<'iltorb'>;
}
