// flow-typed signature: 9fd847120af141315c75f254af16a858
// flow-typed version: <<STUB>>/iltorb_v2.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iltorb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iltorb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'iltorb/index' {
  declare module.exports: $Exports<'iltorb'>;
}
declare module 'iltorb/index.js' {
  declare module.exports: $Exports<'iltorb'>;
}
