// flow-typed signature: 7e3f123dfd840f093a3ad339ab6e0e8b
// flow-typed version: <<STUB>>/iltorb_v2.0.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iltorb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iltorb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'iltorb/index' {
  declare module.exports: $Exports<'iltorb'>;
}
declare module 'iltorb/index.js' {
  declare module.exports: $Exports<'iltorb'>;
}
