// flow-typed signature: eb13398a18a631f566dfc0460ee21918
// flow-typed version: <<STUB>>/interpro-components_v0.6.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'interpro-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'interpro-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'interpro-components/dist/index' {
  declare module.exports: any;
}

declare module 'interpro-components/src/components/index' {
  declare module.exports: any;
}

declare module 'interpro-components/src/components/interpro-data-loader' {
  declare module.exports: any;
}

declare module 'interpro-components/src/components/interpro-entry' {
  declare module.exports: any;
}

declare module 'interpro-components/src/components/interpro-hierarchy' {
  declare module.exports: any;
}

declare module 'interpro-components/src/components/interpro-type' {
  declare module.exports: any;
}

declare module 'interpro-components/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'interpro-components/dist/index.js' {
  declare module.exports: $Exports<'interpro-components/dist/index'>;
}
declare module 'interpro-components/src/components/index.js' {
  declare module.exports: $Exports<'interpro-components/src/components/index'>;
}
declare module 'interpro-components/src/components/interpro-data-loader.js' {
  declare module.exports: $Exports<'interpro-components/src/components/interpro-data-loader'>;
}
declare module 'interpro-components/src/components/interpro-entry.js' {
  declare module.exports: $Exports<'interpro-components/src/components/interpro-entry'>;
}
declare module 'interpro-components/src/components/interpro-hierarchy.js' {
  declare module.exports: $Exports<'interpro-components/src/components/interpro-hierarchy'>;
}
declare module 'interpro-components/src/components/interpro-type.js' {
  declare module.exports: $Exports<'interpro-components/src/components/interpro-type'>;
}
declare module 'interpro-components/src/index.js' {
  declare module.exports: $Exports<'interpro-components/src/index'>;
}
