// flow-typed signature: 1e32f0bf83be4e70d8f40be5c5d1c3f7
// flow-typed version: <<STUB>>/json-loader_v0.5.7/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'json-loader/index' {
  declare module.exports: $Exports<'json-loader'>;
}
declare module 'json-loader/index.js' {
  declare module.exports: $Exports<'json-loader'>;
}
