// flow-typed signature: 47461ea68f930fedd5c3a2f6c0742b0d
// flow-typed version: <<STUB>>/ngl_v2.0.0-dev.36/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ngl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ngl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ngl/dist/ngl.esm' {
  declare module.exports: any;
}

declare module 'ngl/dist/ngl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ngl/dist/ngl.esm.js' {
  declare module.exports: $Exports<'ngl/dist/ngl.esm'>;
}
declare module 'ngl/dist/ngl.js' {
  declare module.exports: $Exports<'ngl/dist/ngl'>;
}
