// flow-typed signature: ff699491696a216475aa08b9c93e154e
// flow-typed version: <<STUB>>/nightingale-sunburst_v3.5.7/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightingale-sunburst'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightingale-sunburst' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightingale-sunburst/dist/nightingale-sunburst' {
  declare module.exports: any;
}

declare module 'nightingale-sunburst/src' {
  declare module.exports: any;
}

declare module 'nightingale-sunburst/src/nightingale-sunburst' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightingale-sunburst/dist/nightingale-sunburst.js' {
  declare module.exports: $Exports<'nightingale-sunburst/dist/nightingale-sunburst'>;
}
declare module 'nightingale-sunburst/src/index' {
  declare module.exports: $Exports<'nightingale-sunburst/src'>;
}
declare module 'nightingale-sunburst/src/index.js' {
  declare module.exports: $Exports<'nightingale-sunburst/src'>;
}
declare module 'nightingale-sunburst/src/nightingale-sunburst.js' {
  declare module.exports: $Exports<'nightingale-sunburst/src/nightingale-sunburst'>;
}
