// flow-typed signature: a65e42d97258f83bcd2dc177b244ea67
// flow-typed version: <<STUB>>/nightingale-linegraph-track_v3.4.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightingale-linegraph-track'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightingale-linegraph-track' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightingale-linegraph-track/dist/nightingale-linegraph-track' {
  declare module.exports: any;
}

declare module 'nightingale-linegraph-track/src' {
  declare module.exports: any;
}

declare module 'nightingale-linegraph-track/src/nightingale-linegraph-track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightingale-linegraph-track/dist/nightingale-linegraph-track.js' {
  declare module.exports: $Exports<'nightingale-linegraph-track/dist/nightingale-linegraph-track'>;
}
declare module 'nightingale-linegraph-track/src/index' {
  declare module.exports: $Exports<'nightingale-linegraph-track/src'>;
}
declare module 'nightingale-linegraph-track/src/index.js' {
  declare module.exports: $Exports<'nightingale-linegraph-track/src'>;
}
declare module 'nightingale-linegraph-track/src/nightingale-linegraph-track.js' {
  declare module.exports: $Exports<'nightingale-linegraph-track/src/nightingale-linegraph-track'>;
}
