// flow-typed signature: 2238c1896513502bbb31aa40403ca0d9
// flow-typed version: <<STUB>>/nightingale-heatmap_v^3.2.11/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightingale-heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightingale-heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightingale-heatmap/src' {
  declare module.exports: any;
}

declare module 'nightingale-heatmap/src/nightingale-heatmap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightingale-heatmap/src/index' {
  declare module.exports: $Exports<'nightingale-heatmap/src'>;
}
declare module 'nightingale-heatmap/src/index.js' {
  declare module.exports: $Exports<'nightingale-heatmap/src'>;
}
declare module 'nightingale-heatmap/src/nightingale-heatmap.js' {
  declare module.exports: $Exports<'nightingale-heatmap/src/nightingale-heatmap'>;
}
