// flow-typed signature: 0c830369615095438487368794d83175
// flow-typed version: <<STUB>>/node-zopfli-es_v0.0.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-zopfli-es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-zopfli-es' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-zopfli-es/bin/zopfli' {
  declare module.exports: any;
}

declare module 'node-zopfli-es/bin/zopflipng' {
  declare module.exports: any;
}

declare module 'node-zopfli-es/lib/zopfli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-zopfli-es/bin/zopfli.js' {
  declare module.exports: $Exports<'node-zopfli-es/bin/zopfli'>;
}
declare module 'node-zopfli-es/bin/zopflipng.js' {
  declare module.exports: $Exports<'node-zopfli-es/bin/zopflipng'>;
}
declare module 'node-zopfli-es/lib/zopfli.js' {
  declare module.exports: $Exports<'node-zopfli-es/lib/zopfli'>;
}
