// flow-typed signature: 9d57c9730947939dacc533db8a0bc476
// flow-typed version: <<STUB>>/node-zopfli_v2.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-zopfli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-zopfli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-zopfli/lib/zopfli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-zopfli/lib/zopfli.js' {
  declare module.exports: $Exports<'node-zopfli/lib/zopfli'>;
}
