// flow-typed signature: 3f3ded7422487422b61dc682caa2b03d
// flow-typed version: <<STUB>>/pinst_v3.0.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pinst'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pinst' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pinst/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pinst/bin.js' {
  declare module.exports: $Exports<'pinst/bin'>;
}
declare module 'pinst/index' {
  declare module.exports: $Exports<'pinst'>;
}
declare module 'pinst/index.js' {
  declare module.exports: $Exports<'pinst'>;
}
