// flow-typed signature: fc943f8af3c536c194e4b375b8fa055f
// flow-typed version: <<STUB>>/postcss-apply_v^0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-apply'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-apply' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-apply/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-apply/dist/visitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-apply/dist/index.js' {
  declare module.exports: $Exports<'postcss-apply/dist/index'>;
}
declare module 'postcss-apply/dist/visitor.js' {
  declare module.exports: $Exports<'postcss-apply/dist/visitor'>;
}
declare module 'postcss-apply/index' {
  declare module.exports: $Exports<'postcss-apply'>;
}
declare module 'postcss-apply/index.js' {
  declare module.exports: $Exports<'postcss-apply'>;
}
