// flow-typed signature: 1f1793a3fa9310740fd7def48274e9a4
// flow-typed version: <<STUB>>/postcss-preset-env_v8.0.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}
