// flow-typed signature: a153bb489168e5ac81aa521bbcf8f346
// flow-typed version: <<STUB>>/protvista-coloured-sequence_v2.12.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-coloured-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-coloured-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-coloured-sequence/dist/protvista-coloured-sequence' {
  declare module.exports: any;
}

declare module 'protvista-coloured-sequence/src' {
  declare module.exports: any;
}

declare module 'protvista-coloured-sequence/src/protvista-coloured-sequence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-coloured-sequence/dist/protvista-coloured-sequence.js' {
  declare module.exports: $Exports<'protvista-coloured-sequence/dist/protvista-coloured-sequence'>;
}
declare module 'protvista-coloured-sequence/src/index' {
  declare module.exports: $Exports<'protvista-coloured-sequence/src'>;
}
declare module 'protvista-coloured-sequence/src/index.js' {
  declare module.exports: $Exports<'protvista-coloured-sequence/src'>;
}
declare module 'protvista-coloured-sequence/src/protvista-coloured-sequence.js' {
  declare module.exports: $Exports<'protvista-coloured-sequence/src/protvista-coloured-sequence'>;
}
