// flow-typed signature: 48c6e16e4300c4a0e1a994ddac9c6a80
// flow-typed version: <<STUB>>/protvista-overlay_v2.12.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-overlay/dist/protvista-overlay' {
  declare module.exports: any;
}

declare module 'protvista-overlay/src' {
  declare module.exports: any;
}

declare module 'protvista-overlay/src/ProtvistaOverlay' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-overlay/dist/protvista-overlay.js' {
  declare module.exports: $Exports<'protvista-overlay/dist/protvista-overlay'>;
}
declare module 'protvista-overlay/src/index' {
  declare module.exports: $Exports<'protvista-overlay/src'>;
}
declare module 'protvista-overlay/src/index.js' {
  declare module.exports: $Exports<'protvista-overlay/src'>;
}
declare module 'protvista-overlay/src/ProtvistaOverlay.js' {
  declare module.exports: $Exports<'protvista-overlay/src/ProtvistaOverlay'>;
}
