// flow-typed signature: ae5cf006143475573300740f470faa94
// flow-typed version: <<STUB>>/protvista-saver_v2.2.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-saver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-saver/src' {
  declare module.exports: any;
}

declare module 'protvista-saver/src/protvista-saver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-saver/src/index' {
  declare module.exports: $Exports<'protvista-saver/src'>;
}
declare module 'protvista-saver/src/index.js' {
  declare module.exports: $Exports<'protvista-saver/src'>;
}
declare module 'protvista-saver/src/protvista-saver.js' {
  declare module.exports: $Exports<'protvista-saver/src/protvista-saver'>;
}
