// flow-typed signature: 6183c11663cbdba0cd9753066913f817
// flow-typed version: <<STUB>>/protvista-interpro-track_v2.13.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-interpro-track'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-interpro-track' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-interpro-track/dist/protvista-interpro-track' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/coverage' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/coverage/index.test' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/InterproEntryLayout' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/protvista-interpro-track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-interpro-track/dist/protvista-interpro-track.js' {
  declare module.exports: $Exports<'protvista-interpro-track/dist/protvista-interpro-track'>;
}
declare module 'protvista-interpro-track/src/coverage/index' {
  declare module.exports: $Exports<'protvista-interpro-track/src/coverage'>;
}
declare module 'protvista-interpro-track/src/coverage/index.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/coverage'>;
}
declare module 'protvista-interpro-track/src/coverage/index.test.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/coverage/index.test'>;
}
declare module 'protvista-interpro-track/src/index' {
  declare module.exports: $Exports<'protvista-interpro-track/src'>;
}
declare module 'protvista-interpro-track/src/index.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src'>;
}
declare module 'protvista-interpro-track/src/InterproEntryLayout.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/InterproEntryLayout'>;
}
declare module 'protvista-interpro-track/src/protvista-interpro-track.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/protvista-interpro-track'>;
}
