// flow-typed signature: 57da4d70625d86aec6925fc9db736417
// flow-typed version: <<STUB>>/protvista-zoomable_v^0.1.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-zoomable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-zoomable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-zoomable/dist/protvista-zoomable' {
  declare module.exports: any;
}

declare module 'protvista-zoomable/src/main' {
  declare module.exports: any;
}

declare module 'protvista-zoomable/src/protvista-zoomable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-zoomable/dist/protvista-zoomable.js' {
  declare module.exports: $Exports<'protvista-zoomable/dist/protvista-zoomable'>;
}
declare module 'protvista-zoomable/src/main.js' {
  declare module.exports: $Exports<'protvista-zoomable/src/main'>;
}
declare module 'protvista-zoomable/src/protvista-zoomable.js' {
  declare module.exports: $Exports<'protvista-zoomable/src/protvista-zoomable'>;
}
