// flow-typed signature: eb1af559b08c6de11d9b71a0fe2e651c
// flow-typed version: <<STUB>>/protvista-manager_v0.0.9/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-manager/dist/protvista-manager' {
  declare module.exports: any;
}

declare module 'protvista-manager/src/index' {
  declare module.exports: any;
}

declare module 'protvista-manager/src/protvista-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-manager/dist/protvista-manager.js' {
  declare module.exports: $Exports<'protvista-manager/dist/protvista-manager'>;
}
declare module 'protvista-manager/src/index.js' {
  declare module.exports: $Exports<'protvista-manager/src/index'>;
}
declare module 'protvista-manager/src/protvista-manager.js' {
  declare module.exports: $Exports<'protvista-manager/src/protvista-manager'>;
}
