// flow-typed signature: be64d66c8fa7ca9f5ca5371cc1119f0c
// flow-typed version: <<STUB>>/protvista-navigation_v0.0.4/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-navigation/dist/protvista-navigation' {
  declare module.exports: any;
}

declare module 'protvista-navigation/rollup.config' {
  declare module.exports: any;
}

declare module 'protvista-navigation/src/index' {
  declare module.exports: any;
}

declare module 'protvista-navigation/src/protvista-navigation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-navigation/dist/protvista-navigation.js' {
  declare module.exports: $Exports<'protvista-navigation/dist/protvista-navigation'>;
}
declare module 'protvista-navigation/rollup.config.js' {
  declare module.exports: $Exports<'protvista-navigation/rollup.config'>;
}
declare module 'protvista-navigation/src/index.js' {
  declare module.exports: $Exports<'protvista-navigation/src/index'>;
}
declare module 'protvista-navigation/src/protvista-navigation.js' {
  declare module.exports: $Exports<'protvista-navigation/src/protvista-navigation'>;
}
