// flow-typed signature: e355f62cfcc4708d9aafdd1c9dad12d0
// flow-typed version: <<STUB>>/protvista-interpro-track_v^0.1.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-interpro-track'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-interpro-track' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-interpro-track/dist/protvista-interpro-track' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/index' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/InterproEntryLayout' {
  declare module.exports: any;
}

declare module 'protvista-interpro-track/src/protvista-interpro-track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-interpro-track/dist/protvista-interpro-track.js' {
  declare module.exports: $Exports<'protvista-interpro-track/dist/protvista-interpro-track'>;
}
declare module 'protvista-interpro-track/src/index.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/index'>;
}
declare module 'protvista-interpro-track/src/InterproEntryLayout.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/InterproEntryLayout'>;
}
declare module 'protvista-interpro-track/src/protvista-interpro-track.js' {
  declare module.exports: $Exports<'protvista-interpro-track/src/protvista-interpro-track'>;
}
