// flow-typed signature: 707ebf637b4cfd6ad92acfd415c60230
// flow-typed version: <<STUB>>/protvista-msa_v2.15.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-msa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-msa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-msa/dist/2dc009bf559fb12fc3db.worker' {
  declare module.exports: any;
}

declare module 'protvista-msa/dist/protvista-msa' {
  declare module.exports: any;
}

declare module 'protvista-msa/src' {
  declare module.exports: any;
}

declare module 'protvista-msa/src/ProtvistaMSA' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-msa/dist/2dc009bf559fb12fc3db.worker.js' {
  declare module.exports: $Exports<'protvista-msa/dist/2dc009bf559fb12fc3db.worker'>;
}
declare module 'protvista-msa/dist/protvista-msa.js' {
  declare module.exports: $Exports<'protvista-msa/dist/protvista-msa'>;
}
declare module 'protvista-msa/src/index' {
  declare module.exports: $Exports<'protvista-msa/src'>;
}
declare module 'protvista-msa/src/index.js' {
  declare module.exports: $Exports<'protvista-msa/src'>;
}
declare module 'protvista-msa/src/ProtvistaMSA.js' {
  declare module.exports: $Exports<'protvista-msa/src/ProtvistaMSA'>;
}
