// flow-typed signature: e43371f289824a2399d2611531d464d0
// flow-typed version: <<STUB>>/protvista-zoomable_v1.0.3-alpha.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-zoomable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-zoomable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-zoomable/dist/protvista-zoomable' {
  declare module.exports: any;
}

declare module 'protvista-zoomable/src/index' {
  declare module.exports: any;
}

declare module 'protvista-zoomable/src/protvista-zoomable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-zoomable/dist/protvista-zoomable.js' {
  declare module.exports: $Exports<'protvista-zoomable/dist/protvista-zoomable'>;
}
declare module 'protvista-zoomable/src/index.js' {
  declare module.exports: $Exports<'protvista-zoomable/src/index'>;
}
declare module 'protvista-zoomable/src/protvista-zoomable.js' {
  declare module.exports: $Exports<'protvista-zoomable/src/protvista-zoomable'>;
}
