// flow-typed signature: 3a2b7ae0c37e693a75b61964e1aca4d9
// flow-typed version: <<STUB>>/protvista-sequence_v0.0.4/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-sequence/dist/protvista-sequence' {
  declare module.exports: any;
}

declare module 'protvista-sequence/rollup.config' {
  declare module.exports: any;
}

declare module 'protvista-sequence/src/index' {
  declare module.exports: any;
}

declare module 'protvista-sequence/src/protvista-sequence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-sequence/dist/protvista-sequence.js' {
  declare module.exports: $Exports<'protvista-sequence/dist/protvista-sequence'>;
}
declare module 'protvista-sequence/rollup.config.js' {
  declare module.exports: $Exports<'protvista-sequence/rollup.config'>;
}
declare module 'protvista-sequence/src/index.js' {
  declare module.exports: $Exports<'protvista-sequence/src/index'>;
}
declare module 'protvista-sequence/src/protvista-sequence.js' {
  declare module.exports: $Exports<'protvista-sequence/src/protvista-sequence'>;
}
