// flow-typed signature: 72ff4c2f05ce57914b10443f3a95e2b8
// flow-typed version: <<STUB>>/protvista-links_v3.4.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-links/dist/protvista-links' {
  declare module.exports: any;
}

declare module 'protvista-links/src' {
  declare module.exports: any;
}

declare module 'protvista-links/src/protvista-links.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-links/dist/protvista-links.js' {
  declare module.exports: $Exports<'protvista-links/dist/protvista-links'>;
}
declare module 'protvista-links/src/index' {
  declare module.exports: $Exports<'protvista-links/src'>;
}
declare module 'protvista-links/src/index.js' {
  declare module.exports: $Exports<'protvista-links/src'>;
}
declare module 'protvista-links/src/protvista-links.test.js' {
  declare module.exports: $Exports<'protvista-links/src/protvista-links.test'>;
}
