// flow-typed signature: 71929b2a95b16a17b8422a6c1545ebef
// flow-typed version: <<STUB>>/protvista-sequence_v1.0.0-beta.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protvista-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'protvista-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protvista-sequence/dist/protvista-sequence' {
  declare module.exports: any;
}

declare module 'protvista-sequence/src/index' {
  declare module.exports: any;
}

declare module 'protvista-sequence/src/protvista-sequence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protvista-sequence/dist/protvista-sequence.js' {
  declare module.exports: $Exports<'protvista-sequence/dist/protvista-sequence'>;
}
declare module 'protvista-sequence/src/index.js' {
  declare module.exports: $Exports<'protvista-sequence/src/index'>;
}
declare module 'protvista-sequence/src/protvista-sequence.js' {
  declare module.exports: $Exports<'protvista-sequence/src/protvista-sequence'>;
}
