// flow-typed signature: 7c559dabeff0a31625376fec5a814790
// flow-typed version: <<STUB>>/puppeteer_v19.2.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/getConfiguration' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/types' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/getConfiguration' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer/install.js' {
  declare module.exports: $Exports<'puppeteer/install'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/getConfiguration.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/getConfiguration'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/install.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/install'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/puppeteer'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/types.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/types'>;
}
declare module 'puppeteer/lib/esm/puppeteer/getConfiguration.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/getConfiguration'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/install.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/install'>;
}
declare module 'puppeteer/lib/esm/puppeteer/puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/puppeteer'>;
}
declare module 'puppeteer/lib/esm/puppeteer/types.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/types'>;
}
