// flow-typed signature: 8fd5475abf5ee3333e4b5f01696d3e5c
// flow-typed version: <<STUB>>/raw-loader_v2.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raw-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raw-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raw-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'raw-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raw-loader/dist/cjs.js' {
  declare module.exports: $Exports<'raw-loader/dist/cjs'>;
}
declare module 'raw-loader/dist/index.js' {
  declare module.exports: $Exports<'raw-loader/dist/index'>;
}
