// flow-typed signature: 01706b80d47da08b4ea365442a7d7d52
// flow-typed version: <<STUB>>/react-to-print_v2.14.15/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-to-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-to-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-to-print/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-to-print/lib/index' {
  declare module.exports: $Exports<'react-to-print/lib'>;
}
declare module 'react-to-print/lib/index.js' {
  declare module.exports: $Exports<'react-to-print/lib'>;
}
