// flow-typed signature: 2a6e2bd9d68417ff9506ce1221332396
// flow-typed version: <<STUB>>/react-diff-viewer-continued_v3.3.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-diff-viewer-continued'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-diff-viewer-continued' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-diff-viewer-continued/babel.config' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/jest.config' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/lib/src/compute-hidden-blocks' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/lib/src/compute-lines' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/lib/src' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/lib/src/styles' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/release.config' {
  declare module.exports: any;
}

declare module 'react-diff-viewer-continued/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-diff-viewer-continued/babel.config.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/babel.config'>;
}
declare module 'react-diff-viewer-continued/jest.config.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/jest.config'>;
}
declare module 'react-diff-viewer-continued/lib/src/compute-hidden-blocks.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/lib/src/compute-hidden-blocks'>;
}
declare module 'react-diff-viewer-continued/lib/src/compute-lines.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/lib/src/compute-lines'>;
}
declare module 'react-diff-viewer-continued/lib/src/index' {
  declare module.exports: $Exports<'react-diff-viewer-continued/lib/src'>;
}
declare module 'react-diff-viewer-continued/lib/src/index.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/lib/src'>;
}
declare module 'react-diff-viewer-continued/lib/src/styles.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/lib/src/styles'>;
}
declare module 'react-diff-viewer-continued/release.config.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/release.config'>;
}
declare module 'react-diff-viewer-continued/webpack.config.js' {
  declare module.exports: $Exports<'react-diff-viewer-continued/webpack.config'>;
}
