// flow-typed signature: 1feb7f0d58902d1f4afd6988c157f4a7
// flow-typed version: <<STUB>>/react-select_v5.8.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select/animated/dist/react-select-animated.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.cjs' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.esm' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.esm' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.esm' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.esm' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-665c4ed8.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-a301f526.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-d1cb43f3.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.default' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-49a62830.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-5dacb5ba.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-d63eed7b.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-6d052b01.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-ba7c6b77.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-be659a57.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-95ae3210.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-cb238d63.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-d97ef2c9.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-7748b351.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-7e1e8489.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-ce23061c.cjs.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select/animated/dist/react-select-animated.cjs.default.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs.default'>;
}
declare module 'react-select/animated/dist/react-select-animated.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs.dev'>;
}
declare module 'react-select/animated/dist/react-select-animated.cjs.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs'>;
}
declare module 'react-select/animated/dist/react-select-animated.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs.prod'>;
}
declare module 'react-select/animated/dist/react-select-animated.esm.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.esm'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.default.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs.default'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.esm.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.esm'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.default.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs.default'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs.dev'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs.prod'>;
}
declare module 'react-select/async/dist/react-select-async.esm.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.esm'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.default.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs.default'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs.dev'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs.prod'>;
}
declare module 'react-select/base/dist/react-select-base.esm.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.esm'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.default.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs.default'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs.dev'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs.prod'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.esm.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.esm'>;
}
declare module 'react-select/dist/index-665c4ed8.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/index-665c4ed8.cjs.prod'>;
}
declare module 'react-select/dist/index-a301f526.esm.js' {
  declare module.exports: $Exports<'react-select/dist/index-a301f526.esm'>;
}
declare module 'react-select/dist/index-d1cb43f3.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/index-d1cb43f3.cjs.dev'>;
}
declare module 'react-select/dist/react-select.cjs.default.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.default'>;
}
declare module 'react-select/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.dev'>;
}
declare module 'react-select/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs'>;
}
declare module 'react-select/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.prod'>;
}
declare module 'react-select/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.esm'>;
}
declare module 'react-select/dist/Select-49a62830.esm.js' {
  declare module.exports: $Exports<'react-select/dist/Select-49a62830.esm'>;
}
declare module 'react-select/dist/Select-5dacb5ba.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/Select-5dacb5ba.cjs.prod'>;
}
declare module 'react-select/dist/Select-d63eed7b.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/Select-d63eed7b.cjs.dev'>;
}
declare module 'react-select/dist/useAsync-6d052b01.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-6d052b01.cjs.dev'>;
}
declare module 'react-select/dist/useAsync-ba7c6b77.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-ba7c6b77.esm'>;
}
declare module 'react-select/dist/useAsync-be659a57.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-be659a57.cjs.prod'>;
}
declare module 'react-select/dist/useCreatable-95ae3210.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-95ae3210.cjs.prod'>;
}
declare module 'react-select/dist/useCreatable-cb238d63.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-cb238d63.cjs.dev'>;
}
declare module 'react-select/dist/useCreatable-d97ef2c9.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-d97ef2c9.esm'>;
}
declare module 'react-select/dist/useStateManager-7748b351.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-7748b351.cjs.dev'>;
}
declare module 'react-select/dist/useStateManager-7e1e8489.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-7e1e8489.esm'>;
}
declare module 'react-select/dist/useStateManager-ce23061c.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-ce23061c.cjs.prod'>;
}
