// flow-typed signature: d9c0d3f15da00a7a6ad98e7042097dfa
// flow-typed version: <<STUB>>/react-diff-viewer_v^3.1.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-diff-viewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-diff-viewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-diff-viewer/lib/compute-lines' {
  declare module.exports: any;
}

declare module 'react-diff-viewer/lib' {
  declare module.exports: any;
}

declare module 'react-diff-viewer/lib/styles' {
  declare module.exports: any;
}

declare module 'react-diff-viewer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-diff-viewer/lib/compute-lines.js' {
  declare module.exports: $Exports<'react-diff-viewer/lib/compute-lines'>;
}
declare module 'react-diff-viewer/lib/index' {
  declare module.exports: $Exports<'react-diff-viewer/lib'>;
}
declare module 'react-diff-viewer/lib/index.js' {
  declare module.exports: $Exports<'react-diff-viewer/lib'>;
}
declare module 'react-diff-viewer/lib/styles.js' {
  declare module.exports: $Exports<'react-diff-viewer/lib/styles'>;
}
declare module 'react-diff-viewer/webpack.config.js' {
  declare module.exports: $Exports<'react-diff-viewer/webpack.config'>;
}
