// flow-typed signature: 2a1dd7747291ed620c1d94fd1407d232
// flow-typed version: <<STUB>>/redux_v5.0.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux/dist/redux.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux/dist/redux.legacy-esm.js' {
  declare module.exports: $Exports<'redux/dist/redux.legacy-esm'>;
}
