// flow-typed signature: 31c6a943410cdb88e63a0d3745aa4940
// flow-typed version: <<STUB>>/reselect_v5.0.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reselect/dist/reselect.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reselect/dist/reselect.legacy-esm.js' {
  declare module.exports: $Exports<'reselect/dist/reselect.legacy-esm'>;
}
