// flow-typed signature: 331bb0a86fedb9bc309b25c5245ce724
// flow-typed version: <<STUB>>/rimraf_v4.1.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rimraf/dist/cjs/src/bin' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/default-tmp' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/fix-eperm' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/fs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/ignore-enoent' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/index-cjs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/opt-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/path-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/platform' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/readdir-or-error' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/retry-busy' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/rimraf-manual' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/rimraf-move-remove' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/rimraf-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/rimraf-posix' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/rimraf-windows' {
  declare module.exports: any;
}

declare module 'rimraf/dist/cjs/src/use-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/default-tmp' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/fix-eperm' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/fs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/ignore-enoent' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/opt-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/path-arg' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/platform' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/readdir-or-error' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/retry-busy' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/rimraf-manual' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/rimraf-move-remove' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/rimraf-native' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/rimraf-posix' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/rimraf-windows' {
  declare module.exports: any;
}

declare module 'rimraf/dist/mjs/use-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rimraf/dist/cjs/src/bin.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/bin'>;
}
declare module 'rimraf/dist/cjs/src/default-tmp.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/default-tmp'>;
}
declare module 'rimraf/dist/cjs/src/fix-eperm.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/fix-eperm'>;
}
declare module 'rimraf/dist/cjs/src/fs.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/fs'>;
}
declare module 'rimraf/dist/cjs/src/ignore-enoent.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/ignore-enoent'>;
}
declare module 'rimraf/dist/cjs/src/index-cjs.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/index-cjs'>;
}
declare module 'rimraf/dist/cjs/src/index' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src'>;
}
declare module 'rimraf/dist/cjs/src/index.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src'>;
}
declare module 'rimraf/dist/cjs/src/opt-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/opt-arg'>;
}
declare module 'rimraf/dist/cjs/src/path-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/path-arg'>;
}
declare module 'rimraf/dist/cjs/src/platform.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/platform'>;
}
declare module 'rimraf/dist/cjs/src/readdir-or-error.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/readdir-or-error'>;
}
declare module 'rimraf/dist/cjs/src/retry-busy.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/retry-busy'>;
}
declare module 'rimraf/dist/cjs/src/rimraf-manual.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/rimraf-manual'>;
}
declare module 'rimraf/dist/cjs/src/rimraf-move-remove.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/rimraf-move-remove'>;
}
declare module 'rimraf/dist/cjs/src/rimraf-native.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/rimraf-native'>;
}
declare module 'rimraf/dist/cjs/src/rimraf-posix.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/rimraf-posix'>;
}
declare module 'rimraf/dist/cjs/src/rimraf-windows.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/rimraf-windows'>;
}
declare module 'rimraf/dist/cjs/src/use-native.js' {
  declare module.exports: $Exports<'rimraf/dist/cjs/src/use-native'>;
}
declare module 'rimraf/dist/mjs/default-tmp.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/default-tmp'>;
}
declare module 'rimraf/dist/mjs/fix-eperm.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/fix-eperm'>;
}
declare module 'rimraf/dist/mjs/fs.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/fs'>;
}
declare module 'rimraf/dist/mjs/ignore-enoent.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/ignore-enoent'>;
}
declare module 'rimraf/dist/mjs/index' {
  declare module.exports: $Exports<'rimraf/dist/mjs'>;
}
declare module 'rimraf/dist/mjs/index.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs'>;
}
declare module 'rimraf/dist/mjs/opt-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/opt-arg'>;
}
declare module 'rimraf/dist/mjs/path-arg.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/path-arg'>;
}
declare module 'rimraf/dist/mjs/platform.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/platform'>;
}
declare module 'rimraf/dist/mjs/readdir-or-error.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/readdir-or-error'>;
}
declare module 'rimraf/dist/mjs/retry-busy.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/retry-busy'>;
}
declare module 'rimraf/dist/mjs/rimraf-manual.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/rimraf-manual'>;
}
declare module 'rimraf/dist/mjs/rimraf-move-remove.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/rimraf-move-remove'>;
}
declare module 'rimraf/dist/mjs/rimraf-native.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/rimraf-native'>;
}
declare module 'rimraf/dist/mjs/rimraf-posix.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/rimraf-posix'>;
}
declare module 'rimraf/dist/mjs/rimraf-windows.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/rimraf-windows'>;
}
declare module 'rimraf/dist/mjs/use-native.js' {
  declare module.exports: $Exports<'rimraf/dist/mjs/use-native'>;
}
