// flow-typed signature: 4149e2b73feab496fac0ef20dc452dd1
// flow-typed version: <<STUB>>/skylign_v^1.0.4/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'skylign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'skylign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'skylign/dist/main' {
  declare module.exports: any;
}

declare module 'skylign/src/_tests_/test' {
  declare module.exports: any;
}

declare module 'skylign/src' {
  declare module.exports: any;
}

declare module 'skylign/src/skylign-component' {
  declare module.exports: any;
}

declare module 'skylign/src/skylign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'skylign/dist/main.js' {
  declare module.exports: $Exports<'skylign/dist/main'>;
}
declare module 'skylign/src/_tests_/test.js' {
  declare module.exports: $Exports<'skylign/src/_tests_/test'>;
}
declare module 'skylign/src/index' {
  declare module.exports: $Exports<'skylign/src'>;
}
declare module 'skylign/src/index.js' {
  declare module.exports: $Exports<'skylign/src'>;
}
declare module 'skylign/src/skylign-component.js' {
  declare module.exports: $Exports<'skylign/src/skylign-component'>;
}
declare module 'skylign/src/skylign.js' {
  declare module.exports: $Exports<'skylign/src/skylign'>;
}
