// flow-typed signature: 383cc2f9304a7be9c9a8184b030034bf
// flow-typed version: <<STUB>>/stockholm-js_v1.0.13/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stockholm-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stockholm-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stockholm-js/src/Stockholm' {
  declare module.exports: any;
}

declare module 'stockholm-js/test/test-lysine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stockholm-js/index' {
  declare module.exports: $Exports<'stockholm-js'>;
}
declare module 'stockholm-js/index.js' {
  declare module.exports: $Exports<'stockholm-js'>;
}
declare module 'stockholm-js/src/Stockholm.js' {
  declare module.exports: $Exports<'stockholm-js/src/Stockholm'>;
}
declare module 'stockholm-js/test/test-lysine.js' {
  declare module.exports: $Exports<'stockholm-js/test/test-lysine'>;
}
