// flow-typed signature: f775ba99a3197144ad391c15eab8f62d
// flow-typed version: <<STUB>>/taxonomy-visualisation_v0.1.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'taxonomy-visualisation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'taxonomy-visualisation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'taxonomy-visualisation/dist/taxonomy-visualisation-without-d3' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/dist/taxonomy-visualisation' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/collapse/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/collapse/test' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-focus/draw-description/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-focus/draw-histogram/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-focus/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-tree/draw-focus-ring/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-tree/draw-links/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-tree/draw-nodes/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw-tree/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/draw/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/focus/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/get-depth-counts/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/get-depth-counts/test' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/get-max-depth/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/get-max-depth/test' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/hierarchy/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/hierarchy/test' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/theme/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/theme/test' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/toggle/index' {
  declare module.exports: any;
}

declare module 'taxonomy-visualisation/src/update-size/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'taxonomy-visualisation/dist/taxonomy-visualisation-without-d3.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/dist/taxonomy-visualisation-without-d3'>;
}
declare module 'taxonomy-visualisation/dist/taxonomy-visualisation.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/dist/taxonomy-visualisation'>;
}
declare module 'taxonomy-visualisation/src/collapse/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/collapse/index'>;
}
declare module 'taxonomy-visualisation/src/collapse/test.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/collapse/test'>;
}
declare module 'taxonomy-visualisation/src/draw-focus/draw-description/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-focus/draw-description/index'>;
}
declare module 'taxonomy-visualisation/src/draw-focus/draw-histogram/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-focus/draw-histogram/index'>;
}
declare module 'taxonomy-visualisation/src/draw-focus/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-focus/index'>;
}
declare module 'taxonomy-visualisation/src/draw-tree/draw-focus-ring/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-tree/draw-focus-ring/index'>;
}
declare module 'taxonomy-visualisation/src/draw-tree/draw-links/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-tree/draw-links/index'>;
}
declare module 'taxonomy-visualisation/src/draw-tree/draw-nodes/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-tree/draw-nodes/index'>;
}
declare module 'taxonomy-visualisation/src/draw-tree/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw-tree/index'>;
}
declare module 'taxonomy-visualisation/src/draw/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/draw/index'>;
}
declare module 'taxonomy-visualisation/src/focus/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/focus/index'>;
}
declare module 'taxonomy-visualisation/src/get-depth-counts/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/get-depth-counts/index'>;
}
declare module 'taxonomy-visualisation/src/get-depth-counts/test.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/get-depth-counts/test'>;
}
declare module 'taxonomy-visualisation/src/get-max-depth/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/get-max-depth/index'>;
}
declare module 'taxonomy-visualisation/src/get-max-depth/test.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/get-max-depth/test'>;
}
declare module 'taxonomy-visualisation/src/hierarchy/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/hierarchy/index'>;
}
declare module 'taxonomy-visualisation/src/hierarchy/test.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/hierarchy/test'>;
}
declare module 'taxonomy-visualisation/src/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/index'>;
}
declare module 'taxonomy-visualisation/src/theme/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/theme/index'>;
}
declare module 'taxonomy-visualisation/src/theme/test.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/theme/test'>;
}
declare module 'taxonomy-visualisation/src/toggle/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/toggle/index'>;
}
declare module 'taxonomy-visualisation/src/update-size/index.js' {
  declare module.exports: $Exports<'taxonomy-visualisation/src/update-size/index'>;
}
