// flow-typed signature: 35f23a81422a9f291d0bce9ec3943151
// flow-typed version: <<STUB>>/timing-functions_v2.0.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timing-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timing-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timing-functions/dist/timing-functions.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timing-functions/dist/timing-functions.cjs.js' {
  declare module.exports: $Exports<'timing-functions/dist/timing-functions.cjs'>;
}
