// flow-typed signature: b9b5e82a1551700ba152568d9ac1eace
// flow-typed version: <<STUB>>/timing-functions_v1.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timing-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timing-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timing-functions/dist' {
  declare module.exports: any;
}

declare module 'timing-functions/src/frame' {
  declare module.exports: any;
}

declare module 'timing-functions/src' {
  declare module.exports: any;
}

declare module 'timing-functions/src/schedule' {
  declare module.exports: any;
}

declare module 'timing-functions/src/scheduler' {
  declare module.exports: any;
}

declare module 'timing-functions/src/sleep' {
  declare module.exports: any;
}

declare module 'timing-functions/src/timeout' {
  declare module.exports: any;
}

declare module 'timing-functions/src/utils/env' {
  declare module.exports: any;
}

declare module 'timing-functions/src/utils/required' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timing-functions/dist/index' {
  declare module.exports: $Exports<'timing-functions/dist'>;
}
declare module 'timing-functions/dist/index.js' {
  declare module.exports: $Exports<'timing-functions/dist'>;
}
declare module 'timing-functions/src/frame/index' {
  declare module.exports: $Exports<'timing-functions/src/frame'>;
}
declare module 'timing-functions/src/frame/index.js' {
  declare module.exports: $Exports<'timing-functions/src/frame'>;
}
declare module 'timing-functions/src/index' {
  declare module.exports: $Exports<'timing-functions/src'>;
}
declare module 'timing-functions/src/index.js' {
  declare module.exports: $Exports<'timing-functions/src'>;
}
declare module 'timing-functions/src/schedule/index' {
  declare module.exports: $Exports<'timing-functions/src/schedule'>;
}
declare module 'timing-functions/src/schedule/index.js' {
  declare module.exports: $Exports<'timing-functions/src/schedule'>;
}
declare module 'timing-functions/src/scheduler/index' {
  declare module.exports: $Exports<'timing-functions/src/scheduler'>;
}
declare module 'timing-functions/src/scheduler/index.js' {
  declare module.exports: $Exports<'timing-functions/src/scheduler'>;
}
declare module 'timing-functions/src/sleep/index' {
  declare module.exports: $Exports<'timing-functions/src/sleep'>;
}
declare module 'timing-functions/src/sleep/index.js' {
  declare module.exports: $Exports<'timing-functions/src/sleep'>;
}
declare module 'timing-functions/src/timeout/index' {
  declare module.exports: $Exports<'timing-functions/src/timeout'>;
}
declare module 'timing-functions/src/timeout/index.js' {
  declare module.exports: $Exports<'timing-functions/src/timeout'>;
}
declare module 'timing-functions/src/utils/env.js' {
  declare module.exports: $Exports<'timing-functions/src/utils/env'>;
}
declare module 'timing-functions/src/utils/required.js' {
  declare module.exports: $Exports<'timing-functions/src/utils/required'>;
}
