// flow-typed signature: 0de8929c2946ea40f5d1fd42ef80c4cb
// flow-typed version: <<STUB>>/to-string-loader_v1.1.6/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-string-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-string-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-string-loader/src/to-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-string-loader/src/to-string.js' {
  declare module.exports: $Exports<'to-string-loader/src/to-string'>;
}
