// flow-typed signature: b0869441ef465a123db888b7b7b87073
// flow-typed version: <<STUB>>/utility-types_v3.10.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utility-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utility-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utility-types/dist/aliases-and-guards' {
  declare module.exports: any;
}

declare module 'utility-types/dist/functional-helpers' {
  declare module.exports: any;
}

declare module 'utility-types/dist' {
  declare module.exports: any;
}

declare module 'utility-types/dist/mapped-types' {
  declare module.exports: any;
}

declare module 'utility-types/dist/utility-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utility-types/dist/aliases-and-guards.js' {
  declare module.exports: $Exports<'utility-types/dist/aliases-and-guards'>;
}
declare module 'utility-types/dist/functional-helpers.js' {
  declare module.exports: $Exports<'utility-types/dist/functional-helpers'>;
}
declare module 'utility-types/dist/index' {
  declare module.exports: $Exports<'utility-types/dist'>;
}
declare module 'utility-types/dist/index.js' {
  declare module.exports: $Exports<'utility-types/dist'>;
}
declare module 'utility-types/dist/mapped-types.js' {
  declare module.exports: $Exports<'utility-types/dist/mapped-types'>;
}
declare module 'utility-types/dist/utility-types.js' {
  declare module.exports: $Exports<'utility-types/dist/utility-types'>;
}
