// flow-typed signature: b95285f639b381f71a1f8ee97423c69c
// flow-typed version: <<STUB>>/webapp-webpack-plugin_v1.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webapp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webapp-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webapp-webpack-plugin/dist/compat' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/dist/compiler' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/dist/loader' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/dist/oracle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webapp-webpack-plugin/dist/compat.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/dist/compat'>;
}
declare module 'webapp-webpack-plugin/dist/compiler.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/dist/compiler'>;
}
declare module 'webapp-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/dist/index'>;
}
declare module 'webapp-webpack-plugin/dist/loader.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/dist/loader'>;
}
declare module 'webapp-webpack-plugin/dist/oracle.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/dist/oracle'>;
}
