// flow-typed signature: 54110c601bff6e27fd993ae23903832a
// flow-typed version: <<STUB>>/workbox-window_v6.4.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-window'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-window' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-window/_version' {
  declare module.exports: any;
}

declare module 'workbox-window/build/workbox-window.dev.umd' {
  declare module.exports: any;
}

declare module 'workbox-window/build/workbox-window.prod.umd' {
  declare module.exports: any;
}

declare module 'workbox-window/messageSW' {
  declare module.exports: any;
}

declare module 'workbox-window/utils/urlsMatch' {
  declare module.exports: any;
}

declare module 'workbox-window/utils/WorkboxEvent' {
  declare module.exports: any;
}

declare module 'workbox-window/utils/WorkboxEventTarget' {
  declare module.exports: any;
}

declare module 'workbox-window/Workbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-window/_version.js' {
  declare module.exports: $Exports<'workbox-window/_version'>;
}
declare module 'workbox-window/build/workbox-window.dev.umd.js' {
  declare module.exports: $Exports<'workbox-window/build/workbox-window.dev.umd'>;
}
declare module 'workbox-window/build/workbox-window.prod.umd.js' {
  declare module.exports: $Exports<'workbox-window/build/workbox-window.prod.umd'>;
}
declare module 'workbox-window/index' {
  declare module.exports: $Exports<'workbox-window'>;
}
declare module 'workbox-window/index.js' {
  declare module.exports: $Exports<'workbox-window'>;
}
declare module 'workbox-window/messageSW.js' {
  declare module.exports: $Exports<'workbox-window/messageSW'>;
}
declare module 'workbox-window/utils/urlsMatch.js' {
  declare module.exports: $Exports<'workbox-window/utils/urlsMatch'>;
}
declare module 'workbox-window/utils/WorkboxEvent.js' {
  declare module.exports: $Exports<'workbox-window/utils/WorkboxEvent'>;
}
declare module 'workbox-window/utils/WorkboxEventTarget.js' {
  declare module.exports: $Exports<'workbox-window/utils/WorkboxEventTarget'>;
}
declare module 'workbox-window/Workbox.js' {
  declare module.exports: $Exports<'workbox-window/Workbox'>;
}
