// flow-typed signature: 5e6581598f0e1c0e6d84109f69dcb8c2
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.23.3/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
