// flow-typed signature: 3c774e17bda423ab3b9fe0212ef5b1c3
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.18.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
