// flow-typed signature: f290276e7e3f1665a167045334b7271a
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.19.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
