// flow-typed signature: 8d37da683e1338d42d184d65a84a64a3
// flow-typed version: <<STUB>>/@hedgedoc/html-to-react_v2.1.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hedgedoc/html-to-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hedgedoc/html-to-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hedgedoc/html-to-react/dist/cjs/convertHtmlToReact' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/convertNodeToReactElement' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/dom/attributes/booleanAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/dom/attributes/reactAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/dom/elements/VoidElements' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessStyleNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTagNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTextNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/index.spec' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/NodeToReactElementTransformer' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/processNodes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/utils/convertInlineStyleToMap' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/utils/generatePropsFromAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/utils/isValidTagOrAttributeName' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/cjs/utils/mapHtmlAttributesToReactElementAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/convertHtmlToReact' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/convertNodeToReactElement' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/dom/attributes/booleanAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/dom/attributes/reactAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/dom/elements/VoidElements' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessStyleNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTagNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTextNode' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/index.spec' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/NodeToReactElementTransformer' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/processNodes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/utils/convertInlineStyleToMap' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/utils/generatePropsFromAttributes' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/utils/isValidTagOrAttributeName' {
  declare module.exports: any;
}

declare module '@hedgedoc/html-to-react/dist/esm/utils/mapHtmlAttributesToReactElementAttributes' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hedgedoc/html-to-react/dist/cjs/convertHtmlToReact.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/convertHtmlToReact'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/convertNodeToReactElement.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/convertNodeToReactElement'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/dom/attributes/booleanAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/dom/attributes/booleanAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/dom/attributes/reactAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/dom/attributes/reactAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/dom/elements/VoidElements.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/dom/elements/VoidElements'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessStyleNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessStyleNode'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTagNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTagNode'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTextNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/elementTypes/ProcessTextNode'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/index' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/index.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/index.spec.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/index.spec'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/NodeToReactElementTransformer.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/NodeToReactElementTransformer'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/processNodes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/processNodes'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/utils/convertInlineStyleToMap.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/utils/convertInlineStyleToMap'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/utils/generatePropsFromAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/utils/generatePropsFromAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/utils/isValidTagOrAttributeName.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/utils/isValidTagOrAttributeName'>;
}
declare module '@hedgedoc/html-to-react/dist/cjs/utils/mapHtmlAttributesToReactElementAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/cjs/utils/mapHtmlAttributesToReactElementAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/convertHtmlToReact.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/convertHtmlToReact'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/convertNodeToReactElement.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/convertNodeToReactElement'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/dom/attributes/booleanAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/dom/attributes/booleanAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/dom/attributes/reactAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/dom/attributes/reactAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/dom/elements/VoidElements.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/dom/elements/VoidElements'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessStyleNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessStyleNode'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTagNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTagNode'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTextNode.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/elementTypes/ProcessTextNode'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/index' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/index.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/index.spec.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/index.spec'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/NodeToReactElementTransformer.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/NodeToReactElementTransformer'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/processNodes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/processNodes'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/utils/convertInlineStyleToMap.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/utils/convertInlineStyleToMap'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/utils/generatePropsFromAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/utils/generatePropsFromAttributes'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/utils/isValidTagOrAttributeName.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/utils/isValidTagOrAttributeName'>;
}
declare module '@hedgedoc/html-to-react/dist/esm/utils/mapHtmlAttributesToReactElementAttributes.js' {
  declare module.exports: $Exports<'@hedgedoc/html-to-react/dist/esm/utils/mapHtmlAttributesToReactElementAttributes'>;
}
