// flow-typed signature: c9e990dc2bed81b23b5f4b1b5117cc2f
// flow-typed version: <<STUB>>/@lit/react_v1.0.2/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lit/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lit/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lit/react/create-component' {
  declare module.exports: any;
}

declare module '@lit/react/development/create-component' {
  declare module.exports: any;
}

declare module '@lit/react/development' {
  declare module.exports: any;
}

declare module '@lit/react/development/use-controller' {
  declare module.exports: any;
}

declare module '@lit/react/node/create-component' {
  declare module.exports: any;
}

declare module '@lit/react/node/development/create-component' {
  declare module.exports: any;
}

declare module '@lit/react/node/development' {
  declare module.exports: any;
}

declare module '@lit/react/node/development/use-controller' {
  declare module.exports: any;
}

declare module '@lit/react/node' {
  declare module.exports: any;
}

declare module '@lit/react/node/use-controller' {
  declare module.exports: any;
}

declare module '@lit/react/use-controller' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lit/react/create-component.js' {
  declare module.exports: $Exports<'@lit/react/create-component'>;
}
declare module '@lit/react/development/create-component.js' {
  declare module.exports: $Exports<'@lit/react/development/create-component'>;
}
declare module '@lit/react/development/index' {
  declare module.exports: $Exports<'@lit/react/development'>;
}
declare module '@lit/react/development/index.js' {
  declare module.exports: $Exports<'@lit/react/development'>;
}
declare module '@lit/react/development/use-controller.js' {
  declare module.exports: $Exports<'@lit/react/development/use-controller'>;
}
declare module '@lit/react/index' {
  declare module.exports: $Exports<'@lit/react'>;
}
declare module '@lit/react/index.js' {
  declare module.exports: $Exports<'@lit/react'>;
}
declare module '@lit/react/node/create-component.js' {
  declare module.exports: $Exports<'@lit/react/node/create-component'>;
}
declare module '@lit/react/node/development/create-component.js' {
  declare module.exports: $Exports<'@lit/react/node/development/create-component'>;
}
declare module '@lit/react/node/development/index' {
  declare module.exports: $Exports<'@lit/react/node/development'>;
}
declare module '@lit/react/node/development/index.js' {
  declare module.exports: $Exports<'@lit/react/node/development'>;
}
declare module '@lit/react/node/development/use-controller.js' {
  declare module.exports: $Exports<'@lit/react/node/development/use-controller'>;
}
declare module '@lit/react/node/index' {
  declare module.exports: $Exports<'@lit/react/node'>;
}
declare module '@lit/react/node/index.js' {
  declare module.exports: $Exports<'@lit/react/node'>;
}
declare module '@lit/react/node/use-controller.js' {
  declare module.exports: $Exports<'@lit/react/node/use-controller'>;
}
declare module '@lit/react/use-controller.js' {
  declare module.exports: $Exports<'@lit/react/use-controller'>;
}
