github:
  InterProClient:
    owner: ProteinsWebTeam
    repo: interpro7-client
  InterProAPI:
    owner: ProteinsWebTeam
    repo: interpro7-api
  IPScan:
    owner: ebi-pf-team
    repo: interproscan
  ReadTheDocs:
    owner: ProteinsWebTeam
    repo: interpro-docs
    branch: master

title: InterPro

IPScan:
  contactEmail: interpro-team@ebi.ac.uk
pages:
  entry:
    plural: entries
    subPages:
      - protein
      - domain_architecture
      - taxonomy
      - proteome
      - structure
      - logo
      - alphafold
      - bfvd
      - entry_alignments
      - interactions
      - pathways
      - curation
      - subfamilies
      - feedback
  protein:
    subPages:
      - entry
      - structure
      - alphafold
      - bfvd
      - sequence
      - similar_proteins
  structure:
    subPages:
      - entry
      - protein
  taxonomy:
    plural: taxa
    subPages:
      - entry
      - protein
      - structure
      - proteome
  proteome:
    subPages:
      - entry
      - protein
      - structure
  sequence:
    subPages:
      - entry
      - sequence
  set:
    subPages:
      - entry
      - protein
      - structure
      - taxonomy
      - proteome
  result:
pagination:
  pageSize: 20
cache:
  enabled: true
colors:
  fallback: '#718189'
  cathgene3d: '#a88cc3'
  cdd: '#addc58'
  hamap: '#2cd6d6'
  mobidblt: '#d6dc94'
  panther: '#bfac92'
  pfam: '#6287b1'
  pirsf: '#fbbddd'
  prints: '#54c75f'
  profile: '#f69f74'
  prosite: '#f3c766'
  sfld: '#00b1d3'
  smart: '#ff8d8d'
  ssf: '#686868'
  ncbifam: '#56b9a6'
  tigrfams: '#56b9a6'
  antifam: '#d8a4a4'
  interpro: '#2daec1'
  pdb: '#74b360'
