// flow-typed signature: df41031f14d41093f03338377435af58
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-heatmap_v4.5.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-heatmap/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-heatmap/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-heatmap/dist'>;
}
declare module '@nightingale-elements/nightingale-heatmap/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-heatmap/dist'>;
}
