// flow-typed signature: c8a4eb1c215506be7494b4cf5f66ec49
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-interpro-track_v^4.0.5-alpha.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-interpro-track'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-interpro-track' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-interpro-track/dist' {
  declare module.exports: any;
}

declare module '@nightingale-elements/nightingale-interpro-track/src/coverage/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-interpro-track/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-interpro-track/dist'>;
}
declare module '@nightingale-elements/nightingale-interpro-track/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-interpro-track/dist'>;
}
declare module '@nightingale-elements/nightingale-interpro-track/src/coverage/index.test.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-interpro-track/src/coverage/index.test'>;
}
