// flow-typed signature: 96365595ae659db092ef7d86a535f2e6
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-new-core_v^4.0.5-alpha.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-new-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-new-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-new-core/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-new-core/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-new-core/dist'>;
}
declare module '@nightingale-elements/nightingale-new-core/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-new-core/dist'>;
}
