// flow-typed signature: 63b2d73441b4098fc79eaaae2f056d55
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-sunburst_v4.0.21-alpha.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-sunburst'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-sunburst' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-sunburst/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-sunburst/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-sunburst/dist'>;
}
declare module '@nightingale-elements/nightingale-sunburst/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-sunburst/dist'>;
}
