// flow-typed signature: ad2827700a652f37843f72c288a2ccb3
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-manager_v^4.0.5-alpha.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-manager/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-manager/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-manager/dist'>;
}
declare module '@nightingale-elements/nightingale-manager/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-manager/dist'>;
}
