// flow-typed signature: d1aef250d1d118161eccfa0ea6faa95c
// flow-typed version: <<STUB>>/@nightingale-elements/nightingale-msa_v4.5.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nightingale-elements/nightingale-msa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nightingale-elements/nightingale-msa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nightingale-elements/nightingale-msa/dist' {
  declare module.exports: any;
}

declare module '@nightingale-elements/nightingale-msa/dist/workers/web-worker-0' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nightingale-elements/nightingale-msa/dist/index' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-msa/dist'>;
}
declare module '@nightingale-elements/nightingale-msa/dist/index.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-msa/dist'>;
}
declare module '@nightingale-elements/nightingale-msa/dist/workers/web-worker-0.js' {
  declare module.exports: $Exports<'@nightingale-elements/nightingale-msa/dist/workers/web-worker-0'>;
}
