// flow-typed signature: 82b28df5f8e9685395a9556f5724fb16
// flow-typed version: <<STUB>>/@tippy.js/react_v3.1.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tippy.js/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tippy.js/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tippy.js/react/dist/tippy-react.esm' {
  declare module.exports: any;
}

declare module '@tippy.js/react/dist/tippy-react.umd' {
  declare module.exports: any;
}

declare module '@tippy.js/react/dist/tippy-react.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tippy.js/react/dist/tippy-react.esm.js' {
  declare module.exports: $Exports<'@tippy.js/react/dist/tippy-react.esm'>;
}
declare module '@tippy.js/react/dist/tippy-react.umd.js' {
  declare module.exports: $Exports<'@tippy.js/react/dist/tippy-react.umd'>;
}
declare module '@tippy.js/react/dist/tippy-react.umd.min.js' {
  declare module.exports: $Exports<'@tippy.js/react/dist/tippy-react.umd.min'>;
}
