// flow-typed signature: c1713acd178db36731ebf90122a564eb
// flow-typed version: <<STUB>>/@storybook/addon-storysource_v6.5.13/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storysource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storysource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storysource/dist/cjs/events' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/cjs/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/cjs/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/esm/events' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/esm/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/esm/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/modern/events' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/modern/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/modern/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storysource/dist/cjs/events.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/cjs/events'>;
}
declare module '@storybook/addon-storysource/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/cjs'>;
}
declare module '@storybook/addon-storysource/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/cjs'>;
}
declare module '@storybook/addon-storysource/dist/cjs/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/cjs/manager'>;
}
declare module '@storybook/addon-storysource/dist/cjs/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/cjs/StoryPanel'>;
}
declare module '@storybook/addon-storysource/dist/esm/events.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/esm/events'>;
}
declare module '@storybook/addon-storysource/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/esm'>;
}
declare module '@storybook/addon-storysource/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/esm'>;
}
declare module '@storybook/addon-storysource/dist/esm/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/esm/manager'>;
}
declare module '@storybook/addon-storysource/dist/esm/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/esm/StoryPanel'>;
}
declare module '@storybook/addon-storysource/dist/modern/events.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/modern/events'>;
}
declare module '@storybook/addon-storysource/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/modern'>;
}
declare module '@storybook/addon-storysource/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/modern'>;
}
declare module '@storybook/addon-storysource/dist/modern/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/modern/manager'>;
}
declare module '@storybook/addon-storysource/dist/modern/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/modern/StoryPanel'>;
}
declare module '@storybook/addon-storysource/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/preset'>;
}
declare module '@storybook/addon-storysource/register.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/register'>;
}
