// flow-typed signature: 2c3676e216333b67cf3e069d9420e5e8
// flow-typed version: <<STUB>>/@storybook/addon-storysource_v6.0.21/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storysource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storysource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storysource/dist/events' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storysource/dist/events.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/events'>;
}
declare module '@storybook/addon-storysource/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist'>;
}
declare module '@storybook/addon-storysource/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist'>;
}
declare module '@storybook/addon-storysource/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/manager'>;
}
declare module '@storybook/addon-storysource/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/preset'>;
}
declare module '@storybook/addon-storysource/dist/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/StoryPanel'>;
}
declare module '@storybook/addon-storysource/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/preset'>;
}
declare module '@storybook/addon-storysource/register.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/register'>;
}
