// flow-typed signature: 2085dd3d82dc6883c8f01783727a978f
// flow-typed version: <<STUB>>/@storybook/addon-postcss_v2.0.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-postcss/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-postcss/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-postcss/dist'>;
}
declare module '@storybook/addon-postcss/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-postcss/dist'>;
}
