// flow-typed signature: d2ba101aaeb402770901927302c1b23b
// flow-typed version: <<STUB>>/@storybook/manager-webpack5_v6.4.18/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/manager-webpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/manager-webpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/manager-webpack5/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/0.799c368cbe88266827ba.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/1.9ebd2fb519f6726108de.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/10.a85ea1a67689be8e19ff.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/11.f4e922583ae35da460f3.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/12.1415460941f0bdcb8fa8.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/5.f459d151315e6780c20f.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/6.3bd64d820f3745f262ff.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/7.3d04765dbf3f1dcd706c.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/8.b541eadfcb9164835dfc.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/9.411ac8e451bbb10926c7.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/main.7b4aec9c4352d4bb535b.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/runtime~main.91a0c7330ab317d35c4a.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/vendors~main.f7f16cebbf3aa96a4f89.manager.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/manager-webpack5/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/manager-preset'>;
}
declare module '@storybook/manager-webpack5/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/prebuilt/0.799c368cbe88266827ba.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/0.799c368cbe88266827ba.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/1.9ebd2fb519f6726108de.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/1.9ebd2fb519f6726108de.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/10.a85ea1a67689be8e19ff.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/10.a85ea1a67689be8e19ff.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/11.f4e922583ae35da460f3.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/11.f4e922583ae35da460f3.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/12.1415460941f0bdcb8fa8.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/12.1415460941f0bdcb8fa8.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/5.f459d151315e6780c20f.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/5.f459d151315e6780c20f.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/6.3bd64d820f3745f262ff.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/6.3bd64d820f3745f262ff.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/7.3d04765dbf3f1dcd706c.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/7.3d04765dbf3f1dcd706c.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/8.b541eadfcb9164835dfc.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/8.b541eadfcb9164835dfc.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/9.411ac8e451bbb10926c7.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/9.411ac8e451bbb10926c7.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/main.7b4aec9c4352d4bb535b.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/main.7b4aec9c4352d4bb535b.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/runtime~main.91a0c7330ab317d35c4a.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/runtime~main.91a0c7330ab317d35c4a.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/vendors~main.f7f16cebbf3aa96a4f89.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/vendors~main.f7f16cebbf3aa96a4f89.manager.bundle'>;
}
