// flow-typed signature: 9905eb39121390b0877f78f788efbb38
// flow-typed version: <<STUB>>/@storybook/manager-webpack5_v6.5.9/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/manager-webpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/manager-webpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/manager-webpack5/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/0.5475f1b09f45f09efaa2.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/1.5bf9ee0884263729115d.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/10.5ccc52dfc06f9584d36f.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/11.912000bc846882dfbfce.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/2.b65894c3feb13613d8bf.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/6.98f130cd27fdf7eb3a72.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/7.4da576e438b3807e47be.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/8.db042c1d94ffe0ee5ea3.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/9.a5725bb040c084fe6ef2.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/main.66e787f7ed3a72f42015.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/runtime~main.463b0423366080dfa2f1.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/vendors~main.95b29d510e9a1f3bb433.manager.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/manager-webpack5/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/manager-preset'>;
}
declare module '@storybook/manager-webpack5/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/prebuilt/0.5475f1b09f45f09efaa2.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/0.5475f1b09f45f09efaa2.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/1.5bf9ee0884263729115d.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/1.5bf9ee0884263729115d.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/10.5ccc52dfc06f9584d36f.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/10.5ccc52dfc06f9584d36f.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/11.912000bc846882dfbfce.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/11.912000bc846882dfbfce.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/2.b65894c3feb13613d8bf.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/2.b65894c3feb13613d8bf.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/6.98f130cd27fdf7eb3a72.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/6.98f130cd27fdf7eb3a72.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/7.4da576e438b3807e47be.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/7.4da576e438b3807e47be.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/8.db042c1d94ffe0ee5ea3.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/8.db042c1d94ffe0ee5ea3.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/9.a5725bb040c084fe6ef2.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/9.a5725bb040c084fe6ef2.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/main.66e787f7ed3a72f42015.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/main.66e787f7ed3a72f42015.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/runtime~main.463b0423366080dfa2f1.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/runtime~main.463b0423366080dfa2f1.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/vendors~main.95b29d510e9a1f3bb433.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/vendors~main.95b29d510e9a1f3bb433.manager.bundle'>;
}
