// flow-typed signature: 78bbf6524a21d2b740037e88abbf0af7
// flow-typed version: <<STUB>>/@storybook/theming_v6.5.13/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/theming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/theming/create' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/theming/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/theming/paths' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/theming/create.js' {
  declare module.exports: $Exports<'@storybook/theming/create'>;
}
declare module '@storybook/theming/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/theming/dist/cjs'>;
}
declare module '@storybook/theming/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/cjs'>;
}
declare module '@storybook/theming/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/theming/dist/esm'>;
}
declare module '@storybook/theming/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/esm'>;
}
declare module '@storybook/theming/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/theming/dist/modern'>;
}
declare module '@storybook/theming/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/theming/dist/modern'>;
}
declare module '@storybook/theming/paths.js' {
  declare module.exports: $Exports<'@storybook/theming/paths'>;
}
