name: CI Pipeline

on:
  workflow_run:
    workflows: [test_and_build]
    types: [completed]
    branches: [runner, dev]

jobs:
  build:
    runs-on: self-hosted 
    steps:

      - name: Clean up
        run: |
          export PATH="$CONDA_PREFIX/bin:$PATH"
          rm -rf ~/release-procedures/v2/frontend-runner/_work/interpro7-client/interpro7-client/*

      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: deploy

      - name: Release 
        run: |            
            
            export PATH="$CONDA_PREFIX/bin:$PATH"
            commit_hash=$(git log -1 --pretty=format:"%H")
            changed_files=$(git show --name-only --pretty="" $commit_hash)

            # Determine the deployment branch and set paths accordingly
            if echo "$changed_files" | grep -q '^dev/'; then
              export DEPLOY_BRANCH="dev"
              export VM_BASE_PATH="/nfs/www-prod/web_hx2/interpro/dev/website/releases/";
              export VM_NAME="wp-np3-bd";
            elif echo "$changed_files" | grep -q '^master/'; then
              export DEPLOY_BRANCH="master"
              export VM_BASE_PATH="/nfs/www-prod/web_hx2/interpro/master/website/releases/";
              export VM_NAME="wp-np3-bd";
            else
              echo "No matching changes detected. Exiting."
              exit 0
            fi

            # Adjust the dist/ path based on the deploy branch
            export DIST_PATH="$DEPLOY_BRANCH"
            export IPRO_RELEASE_FOLDER="interpro7-client-$(date --utc +%Y_%m_%d-%H_%M_%S_utc)";
            
            echo "Deploying from $DIST_PATH to $VM_BASE_PATH"
            
            # Create the release folder on the remote server
            ssh $VM_NAME "cd $VM_BASE_PATH; mkdir -p \"${IPRO_RELEASE_FOLDER}\""

            # Copy the deployment artifacts
            scp -q -r $DIST_PATH/* $VM_NAME:"$VM_BASE_PATH/$IPRO_RELEASE_FOLDER"
            export SYMLINK="/nfs/www-prod/web_hx2/interpro/dev/website/interpro7-client"
            ssh $VM_NAME "rm -f \"$SYMLINK\"; ln -s \"$VM_BASE_PATH/$IPRO_RELEASE_FOLDER\" \"$SYMLINK\""
